/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.12.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QListWidget>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QStackedWidget *primaryPageStackedWidget;
    QWidget *loginPage;
    QPushButton *loginPushButton;
    QLabel *label;
    QLabel *label_2;
    QWidget *layoutWidget;
    QHBoxLayout *horizontalLayout_2;
    QLabel *usernameLabel;
    QLineEdit *usernameLineEdit;
    QWidget *layoutWidget1;
    QHBoxLayout *horizontalLayout;
    QLabel *passwordLabel;
    QLineEdit *passwordLineEdit;
    QWidget *adminPage;
    QStackedWidget *adminStackedWidget;
    QWidget *welcomePage_admin;
    QLabel *welcomeLabel_admin;
    QPushButton *informationButton_admin;
    QPushButton *takeTripButton_admin;
    QPushButton *manageStadiumsButton;
    QWidget *manageStadiumsPage;
    QListWidget *stadiumListWidget;
    QListWidget *souvenirListWidget;
    QLabel *label_3;
    QLabel *label_10;
    QPushButton *manageStadiumsBackButton;
    QGroupBox *groupBox;
    QLabel *capacityLabel;
    QLabel *typologyLabel;
    QLineEdit *distToCenterLineEdit;
    QLabel *roofTypeLabel;
    QLabel *surfaceLabel;
    QLineEdit *capacityLineEdit;
    QLineEdit *roofTypeLineEdit;
    QLineEdit *surfaceLineEdit;
    QLineEdit *dateOpenedLineEdit;
    QLabel *dateLabel;
    QLineEdit *typologyLineEdit;
    QLabel *distToCenterLabel;
    QLineEdit *newLocationLineEdit;
    QLabel *newLocationLabel;
    QListWidget *souvenirPriceListWidget;
    QWidget *userPage;
    QStackedWidget *userStackedWidget;
    QWidget *welcomePage_user;
    QPushButton *takeTripButton_user;
    QPushButton *informationButton_user;
    QLabel *label_11;
    QPushButton *viewStadiumsButton;
    QWidget *takeTripPage;
    QWidget *informationPage;
    QPushButton *informationBackButton;
    QTabWidget *tabWidget;
    QWidget *MajorLeagueTeam;
    QListWidget *teamListWidget_1;
    QLabel *label_5;
    QLabel *label_19;
    QListWidget *stadiumList_1;
    QWidget *MajorLeagueStadium;
    QListWidget *teamListWidget_2;
    QLabel *label_6;
    QLabel *label_20;
    QListWidget *stadiumList_2;
    QWidget *AmericanLeagueTeam;
    QListWidget *teamListWidget_3;
    QLabel *label_7;
    QLabel *label_21;
    QListWidget *stadiumList_3;
    QWidget *NationalLeagueStadium;
    QListWidget *teamListWidget_4;
    QLabel *label_4;
    QListWidget *stadiumList_4;
    QLabel *label_22;
    QWidget *typology;
    QListWidget *teamListWidget_5;
    QLabel *label_8;
    QListWidget *stadiumList_5;
    QLabel *label_23;
    QListWidget *typologyList;
    QLabel *label_29;
    QWidget *openRoofType;
    QListWidget *teamListWidget_6;
    QLabel *label_9;
    QListWidget *stadiumList_6;
    QLabel *label_24;
    QListWidget *openRoofList;
    QLabel *label_30;
    QWidget *dateOpened;
    QListWidget *teamListWidget_7;
    QLabel *label_15;
    QListWidget *stadiumList_7;
    QLabel *label_25;
    QListWidget *dateOpenedList;
    QLabel *label_31;
    QWidget *seatingCapacity;
    QListWidget *teamListWidget_8;
    QLabel *label_16;
    QListWidget *stadiumList_8;
    QLabel *label_26;
    QLabel *label_32;
    QListWidget *seatingCapacityList;
    QWidget *greatestDistanceCenter;
    QListWidget *teamListWidget_9;
    QLabel *label_17;
    QListWidget *stadiumList_9;
    QLabel *label_27;
    QWidget *smallestDistanceCenter;
    QListWidget *teamListWidget_10;
    QLabel *label_18;
    QListWidget *stadiumList_10;
    QLabel *label_28;
    QLabel *label_12;
    QWidget *viewStadiumsPage;
    QListWidget *souvenirListWidget_2;
    QListWidget *stadiumListWidget_2;
    QGroupBox *groupBox_2;
    QLabel *capacityLabel_2;
    QLabel *typologyLabel_2;
    QLineEdit *distToCenterLineEdit_2;
    QLabel *roofTypeLabel_2;
    QLabel *surfaceLabel_2;
    QLineEdit *capacityLineEdit_2;
    QLineEdit *roofTypeLineEdit_2;
    QLineEdit *surfaceLineEdit_2;
    QLineEdit *dateOpenedLineEdit_2;
    QLabel *dateLabel_2;
    QLineEdit *typologyLineEdit_2;
    QLabel *distToCenterLabel_2;
    QLineEdit *newLocationLineEdit_2;
    QLabel *newLocationLabel_2;
    QLabel *label_13;
    QPushButton *viewStadiumsBackButton;
    QListWidget *souvenirPriceListWidget_2;
    QLabel *label_14;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1200, 800);
        QSizePolicy sizePolicy(QSizePolicy::Fixed, QSizePolicy::Fixed);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(MainWindow->sizePolicy().hasHeightForWidth());
        MainWindow->setSizePolicy(sizePolicy);
        MainWindow->setMinimumSize(QSize(1200, 800));
        MainWindow->setMaximumSize(QSize(1200, 800));
        MainWindow->setBaseSize(QSize(1000, 700));
        QFont font;
        font.setPointSize(10);
        MainWindow->setFont(font);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        primaryPageStackedWidget = new QStackedWidget(centralWidget);
        primaryPageStackedWidget->setObjectName(QString::fromUtf8("primaryPageStackedWidget"));
        primaryPageStackedWidget->setGeometry(QRect(20, 10, 1201, 761));
        QSizePolicy sizePolicy1(QSizePolicy::Fixed, QSizePolicy::Preferred);
        sizePolicy1.setHorizontalStretch(0);
        sizePolicy1.setVerticalStretch(0);
        sizePolicy1.setHeightForWidth(primaryPageStackedWidget->sizePolicy().hasHeightForWidth());
        primaryPageStackedWidget->setSizePolicy(sizePolicy1);
        loginPage = new QWidget();
        loginPage->setObjectName(QString::fromUtf8("loginPage"));
        loginPushButton = new QPushButton(loginPage);
        loginPushButton->setObjectName(QString::fromUtf8("loginPushButton"));
        loginPushButton->setGeometry(QRect(490, 390, 191, 41));
        label = new QLabel(loginPage);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(530, 110, 141, 16));
        label_2 = new QLabel(loginPage);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(560, 200, 61, 16));
        layoutWidget = new QWidget(loginPage);
        layoutWidget->setObjectName(QString::fromUtf8("layoutWidget"));
        layoutWidget->setGeometry(QRect(490, 310, 191, 26));
        horizontalLayout_2 = new QHBoxLayout(layoutWidget);
        horizontalLayout_2->setSpacing(6);
        horizontalLayout_2->setContentsMargins(11, 11, 11, 11);
        horizontalLayout_2->setObjectName(QString::fromUtf8("horizontalLayout_2"));
        horizontalLayout_2->setContentsMargins(0, 0, 0, 0);
        usernameLabel = new QLabel(layoutWidget);
        usernameLabel->setObjectName(QString::fromUtf8("usernameLabel"));

        horizontalLayout_2->addWidget(usernameLabel);

        usernameLineEdit = new QLineEdit(layoutWidget);
        usernameLineEdit->setObjectName(QString::fromUtf8("usernameLineEdit"));

        horizontalLayout_2->addWidget(usernameLineEdit);

        layoutWidget1 = new QWidget(loginPage);
        layoutWidget1->setObjectName(QString::fromUtf8("layoutWidget1"));
        layoutWidget1->setGeometry(QRect(490, 350, 191, 26));
        horizontalLayout = new QHBoxLayout(layoutWidget1);
        horizontalLayout->setSpacing(6);
        horizontalLayout->setContentsMargins(11, 11, 11, 11);
        horizontalLayout->setObjectName(QString::fromUtf8("horizontalLayout"));
        horizontalLayout->setContentsMargins(0, 0, 0, 0);
        passwordLabel = new QLabel(layoutWidget1);
        passwordLabel->setObjectName(QString::fromUtf8("passwordLabel"));

        horizontalLayout->addWidget(passwordLabel);

        passwordLineEdit = new QLineEdit(layoutWidget1);
        passwordLineEdit->setObjectName(QString::fromUtf8("passwordLineEdit"));

        horizontalLayout->addWidget(passwordLineEdit);

        primaryPageStackedWidget->addWidget(loginPage);
        adminPage = new QWidget();
        adminPage->setObjectName(QString::fromUtf8("adminPage"));
        adminStackedWidget = new QStackedWidget(adminPage);
        adminStackedWidget->setObjectName(QString::fromUtf8("adminStackedWidget"));
        adminStackedWidget->setGeometry(QRect(-10, 0, 1201, 771));
        welcomePage_admin = new QWidget();
        welcomePage_admin->setObjectName(QString::fromUtf8("welcomePage_admin"));
        welcomeLabel_admin = new QLabel(welcomePage_admin);
        welcomeLabel_admin->setObjectName(QString::fromUtf8("welcomeLabel_admin"));
        welcomeLabel_admin->setGeometry(QRect(520, 70, 101, 16));
        informationButton_admin = new QPushButton(welcomePage_admin);
        informationButton_admin->setObjectName(QString::fromUtf8("informationButton_admin"));
        informationButton_admin->setGeometry(QRect(470, 510, 291, 61));
        takeTripButton_admin = new QPushButton(welcomePage_admin);
        takeTripButton_admin->setObjectName(QString::fromUtf8("takeTripButton_admin"));
        takeTripButton_admin->setGeometry(QRect(60, 510, 301, 61));
        sizePolicy.setHeightForWidth(takeTripButton_admin->sizePolicy().hasHeightForWidth());
        takeTripButton_admin->setSizePolicy(sizePolicy);
        manageStadiumsButton = new QPushButton(welcomePage_admin);
        manageStadiumsButton->setObjectName(QString::fromUtf8("manageStadiumsButton"));
        manageStadiumsButton->setGeometry(QRect(860, 510, 301, 61));
        sizePolicy.setHeightForWidth(manageStadiumsButton->sizePolicy().hasHeightForWidth());
        manageStadiumsButton->setSizePolicy(sizePolicy);
        adminStackedWidget->addWidget(welcomePage_admin);
        manageStadiumsPage = new QWidget();
        manageStadiumsPage->setObjectName(QString::fromUtf8("manageStadiumsPage"));
        stadiumListWidget = new QListWidget(manageStadiumsPage);
        stadiumListWidget->setObjectName(QString::fromUtf8("stadiumListWidget"));
        stadiumListWidget->setGeometry(QRect(40, 120, 451, 591));
        souvenirListWidget = new QListWidget(manageStadiumsPage);
        souvenirListWidget->setObjectName(QString::fromUtf8("souvenirListWidget"));
        souvenirListWidget->setGeometry(QRect(920, 120, 191, 271));
        label_3 = new QLabel(manageStadiumsPage);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(230, 90, 51, 16));
        label_10 = new QLabel(manageStadiumsPage);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(1000, 90, 61, 16));
        manageStadiumsBackButton = new QPushButton(manageStadiumsPage);
        manageStadiumsBackButton->setObjectName(QString::fromUtf8("manageStadiumsBackButton"));
        manageStadiumsBackButton->setGeometry(QRect(40, 20, 121, 41));
        groupBox = new QGroupBox(manageStadiumsPage);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(540, 420, 621, 291));
        capacityLabel = new QLabel(groupBox);
        capacityLabel->setObjectName(QString::fromUtf8("capacityLabel"));
        capacityLabel->setGeometry(QRect(50, 40, 51, 16));
        typologyLabel = new QLabel(groupBox);
        typologyLabel->setObjectName(QString::fromUtf8("typologyLabel"));
        typologyLabel->setGeometry(QRect(50, 130, 61, 16));
        distToCenterLineEdit = new QLineEdit(groupBox);
        distToCenterLineEdit->setObjectName(QString::fromUtf8("distToCenterLineEdit"));
        distToCenterLineEdit->setGeometry(QRect(360, 170, 113, 20));
        roofTypeLabel = new QLabel(groupBox);
        roofTypeLabel->setObjectName(QString::fromUtf8("roofTypeLabel"));
        roofTypeLabel->setGeometry(QRect(390, 40, 61, 16));
        surfaceLabel = new QLabel(groupBox);
        surfaceLabel->setObjectName(QString::fromUtf8("surfaceLabel"));
        surfaceLabel->setGeometry(QRect(220, 40, 47, 13));
        capacityLineEdit = new QLineEdit(groupBox);
        capacityLineEdit->setObjectName(QString::fromUtf8("capacityLineEdit"));
        capacityLineEdit->setGeometry(QRect(20, 80, 113, 20));
        roofTypeLineEdit = new QLineEdit(groupBox);
        roofTypeLineEdit->setObjectName(QString::fromUtf8("roofTypeLineEdit"));
        roofTypeLineEdit->setGeometry(QRect(360, 80, 113, 20));
        surfaceLineEdit = new QLineEdit(groupBox);
        surfaceLineEdit->setObjectName(QString::fromUtf8("surfaceLineEdit"));
        surfaceLineEdit->setGeometry(QRect(190, 80, 113, 20));
        dateOpenedLineEdit = new QLineEdit(groupBox);
        dateOpenedLineEdit->setObjectName(QString::fromUtf8("dateOpenedLineEdit"));
        dateOpenedLineEdit->setGeometry(QRect(190, 170, 113, 20));
        dateLabel = new QLabel(groupBox);
        dateLabel->setObjectName(QString::fromUtf8("dateLabel"));
        dateLabel->setGeometry(QRect(210, 130, 81, 16));
        typologyLineEdit = new QLineEdit(groupBox);
        typologyLineEdit->setObjectName(QString::fromUtf8("typologyLineEdit"));
        typologyLineEdit->setGeometry(QRect(20, 170, 113, 20));
        distToCenterLabel = new QLabel(groupBox);
        distToCenterLabel->setObjectName(QString::fromUtf8("distToCenterLabel"));
        distToCenterLabel->setGeometry(QRect(360, 130, 131, 16));
        newLocationLineEdit = new QLineEdit(groupBox);
        newLocationLineEdit->setObjectName(QString::fromUtf8("newLocationLineEdit"));
        newLocationLineEdit->setGeometry(QRect(20, 260, 113, 20));
        newLocationLabel = new QLabel(groupBox);
        newLocationLabel->setObjectName(QString::fromUtf8("newLocationLabel"));
        newLocationLabel->setGeometry(QRect(40, 230, 81, 16));
        souvenirPriceListWidget = new QListWidget(manageStadiumsPage);
        souvenirPriceListWidget->setObjectName(QString::fromUtf8("souvenirPriceListWidget"));
        souvenirPriceListWidget->setGeometry(QRect(1110, 120, 51, 271));
        adminStackedWidget->addWidget(manageStadiumsPage);
        primaryPageStackedWidget->addWidget(adminPage);
        userPage = new QWidget();
        userPage->setObjectName(QString::fromUtf8("userPage"));
        userStackedWidget = new QStackedWidget(userPage);
        userStackedWidget->setObjectName(QString::fromUtf8("userStackedWidget"));
        userStackedWidget->setGeometry(QRect(0, 0, 1201, 771));
        welcomePage_user = new QWidget();
        welcomePage_user->setObjectName(QString::fromUtf8("welcomePage_user"));
        takeTripButton_user = new QPushButton(welcomePage_user);
        takeTripButton_user->setObjectName(QString::fromUtf8("takeTripButton_user"));
        takeTripButton_user->setGeometry(QRect(60, 540, 301, 61));
        sizePolicy.setHeightForWidth(takeTripButton_user->sizePolicy().hasHeightForWidth());
        takeTripButton_user->setSizePolicy(sizePolicy);
        informationButton_user = new QPushButton(welcomePage_user);
        informationButton_user->setObjectName(QString::fromUtf8("informationButton_user"));
        informationButton_user->setGeometry(QRect(440, 540, 291, 61));
        label_11 = new QLabel(welcomePage_user);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(550, 100, 231, 16));
        viewStadiumsButton = new QPushButton(welcomePage_user);
        viewStadiumsButton->setObjectName(QString::fromUtf8("viewStadiumsButton"));
        viewStadiumsButton->setGeometry(QRect(810, 540, 291, 61));
        userStackedWidget->addWidget(welcomePage_user);
        takeTripPage = new QWidget();
        takeTripPage->setObjectName(QString::fromUtf8("takeTripPage"));
        userStackedWidget->addWidget(takeTripPage);
        informationPage = new QWidget();
        informationPage->setObjectName(QString::fromUtf8("informationPage"));
        informationBackButton = new QPushButton(informationPage);
        informationBackButton->setObjectName(QString::fromUtf8("informationBackButton"));
        informationBackButton->setGeometry(QRect(30, 20, 121, 41));
        tabWidget = new QTabWidget(informationPage);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
        tabWidget->setGeometry(QRect(40, 100, 1101, 421));
        tabWidget->setTabPosition(QTabWidget::North);
        MajorLeagueTeam = new QWidget();
        MajorLeagueTeam->setObjectName(QString::fromUtf8("MajorLeagueTeam"));
        teamListWidget_1 = new QListWidget(MajorLeagueTeam);
        teamListWidget_1->setObjectName(QString::fromUtf8("teamListWidget_1"));
        teamListWidget_1->setGeometry(QRect(10, 30, 321, 311));
        label_5 = new QLabel(MajorLeagueTeam);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(130, 10, 111, 16));
        label_19 = new QLabel(MajorLeagueTeam);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(450, 10, 111, 16));
        stadiumList_1 = new QListWidget(MajorLeagueTeam);
        stadiumList_1->setObjectName(QString::fromUtf8("stadiumList_1"));
        stadiumList_1->setGeometry(QRect(330, 30, 321, 311));
        tabWidget->addTab(MajorLeagueTeam, QString());
        MajorLeagueStadium = new QWidget();
        MajorLeagueStadium->setObjectName(QString::fromUtf8("MajorLeagueStadium"));
        teamListWidget_2 = new QListWidget(MajorLeagueStadium);
        teamListWidget_2->setObjectName(QString::fromUtf8("teamListWidget_2"));
        teamListWidget_2->setGeometry(QRect(10, 30, 321, 311));
        label_6 = new QLabel(MajorLeagueStadium);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(130, 10, 111, 16));
        label_20 = new QLabel(MajorLeagueStadium);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(450, 10, 111, 16));
        stadiumList_2 = new QListWidget(MajorLeagueStadium);
        stadiumList_2->setObjectName(QString::fromUtf8("stadiumList_2"));
        stadiumList_2->setGeometry(QRect(330, 30, 321, 311));
        tabWidget->addTab(MajorLeagueStadium, QString());
        AmericanLeagueTeam = new QWidget();
        AmericanLeagueTeam->setObjectName(QString::fromUtf8("AmericanLeagueTeam"));
        teamListWidget_3 = new QListWidget(AmericanLeagueTeam);
        teamListWidget_3->setObjectName(QString::fromUtf8("teamListWidget_3"));
        teamListWidget_3->setGeometry(QRect(10, 30, 321, 311));
        label_7 = new QLabel(AmericanLeagueTeam);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(130, 10, 111, 16));
        label_21 = new QLabel(AmericanLeagueTeam);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(450, 10, 111, 16));
        stadiumList_3 = new QListWidget(AmericanLeagueTeam);
        stadiumList_3->setObjectName(QString::fromUtf8("stadiumList_3"));
        stadiumList_3->setGeometry(QRect(330, 30, 321, 311));
        tabWidget->addTab(AmericanLeagueTeam, QString());
        NationalLeagueStadium = new QWidget();
        NationalLeagueStadium->setObjectName(QString::fromUtf8("NationalLeagueStadium"));
        teamListWidget_4 = new QListWidget(NationalLeagueStadium);
        teamListWidget_4->setObjectName(QString::fromUtf8("teamListWidget_4"));
        teamListWidget_4->setGeometry(QRect(10, 30, 321, 311));
        label_4 = new QLabel(NationalLeagueStadium);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(130, 10, 111, 16));
        stadiumList_4 = new QListWidget(NationalLeagueStadium);
        stadiumList_4->setObjectName(QString::fromUtf8("stadiumList_4"));
        stadiumList_4->setGeometry(QRect(330, 30, 321, 311));
        label_22 = new QLabel(NationalLeagueStadium);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(450, 10, 111, 16));
        tabWidget->addTab(NationalLeagueStadium, QString());
        typology = new QWidget();
        typology->setObjectName(QString::fromUtf8("typology"));
        teamListWidget_5 = new QListWidget(typology);
        teamListWidget_5->setObjectName(QString::fromUtf8("teamListWidget_5"));
        teamListWidget_5->setGeometry(QRect(10, 30, 321, 311));
        label_8 = new QLabel(typology);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(130, 10, 111, 16));
        stadiumList_5 = new QListWidget(typology);
        stadiumList_5->setObjectName(QString::fromUtf8("stadiumList_5"));
        stadiumList_5->setGeometry(QRect(330, 30, 321, 311));
        label_23 = new QLabel(typology);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(450, 10, 111, 16));
        typologyList = new QListWidget(typology);
        typologyList->setObjectName(QString::fromUtf8("typologyList"));
        typologyList->setGeometry(QRect(650, 30, 241, 311));
        label_29 = new QLabel(typology);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(720, 10, 111, 16));
        tabWidget->addTab(typology, QString());
        openRoofType = new QWidget();
        openRoofType->setObjectName(QString::fromUtf8("openRoofType"));
        teamListWidget_6 = new QListWidget(openRoofType);
        teamListWidget_6->setObjectName(QString::fromUtf8("teamListWidget_6"));
        teamListWidget_6->setGeometry(QRect(10, 30, 321, 311));
        label_9 = new QLabel(openRoofType);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(130, 10, 111, 16));
        stadiumList_6 = new QListWidget(openRoofType);
        stadiumList_6->setObjectName(QString::fromUtf8("stadiumList_6"));
        stadiumList_6->setGeometry(QRect(330, 30, 321, 311));
        label_24 = new QLabel(openRoofType);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(450, 10, 111, 16));
        openRoofList = new QListWidget(openRoofType);
        openRoofList->setObjectName(QString::fromUtf8("openRoofList"));
        openRoofList->setGeometry(QRect(650, 30, 241, 311));
        label_30 = new QLabel(openRoofType);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(720, 10, 111, 16));
        tabWidget->addTab(openRoofType, QString());
        dateOpened = new QWidget();
        dateOpened->setObjectName(QString::fromUtf8("dateOpened"));
        teamListWidget_7 = new QListWidget(dateOpened);
        teamListWidget_7->setObjectName(QString::fromUtf8("teamListWidget_7"));
        teamListWidget_7->setGeometry(QRect(10, 30, 321, 311));
        label_15 = new QLabel(dateOpened);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(130, 10, 111, 16));
        stadiumList_7 = new QListWidget(dateOpened);
        stadiumList_7->setObjectName(QString::fromUtf8("stadiumList_7"));
        stadiumList_7->setGeometry(QRect(330, 30, 321, 311));
        label_25 = new QLabel(dateOpened);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(450, 10, 111, 16));
        dateOpenedList = new QListWidget(dateOpened);
        dateOpenedList->setObjectName(QString::fromUtf8("dateOpenedList"));
        dateOpenedList->setGeometry(QRect(650, 30, 241, 311));
        label_31 = new QLabel(dateOpened);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(720, 10, 111, 16));
        tabWidget->addTab(dateOpened, QString());
        seatingCapacity = new QWidget();
        seatingCapacity->setObjectName(QString::fromUtf8("seatingCapacity"));
        teamListWidget_8 = new QListWidget(seatingCapacity);
        teamListWidget_8->setObjectName(QString::fromUtf8("teamListWidget_8"));
        teamListWidget_8->setGeometry(QRect(10, 30, 321, 311));
        label_16 = new QLabel(seatingCapacity);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(130, 10, 111, 16));
        stadiumList_8 = new QListWidget(seatingCapacity);
        stadiumList_8->setObjectName(QString::fromUtf8("stadiumList_8"));
        stadiumList_8->setGeometry(QRect(330, 30, 321, 311));
        label_26 = new QLabel(seatingCapacity);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(450, 10, 111, 16));
        label_32 = new QLabel(seatingCapacity);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(700, 10, 171, 16));
        seatingCapacityList = new QListWidget(seatingCapacity);
        seatingCapacityList->setObjectName(QString::fromUtf8("seatingCapacityList"));
        seatingCapacityList->setGeometry(QRect(650, 30, 241, 311));
        tabWidget->addTab(seatingCapacity, QString());
        greatestDistanceCenter = new QWidget();
        greatestDistanceCenter->setObjectName(QString::fromUtf8("greatestDistanceCenter"));
        teamListWidget_9 = new QListWidget(greatestDistanceCenter);
        teamListWidget_9->setObjectName(QString::fromUtf8("teamListWidget_9"));
        teamListWidget_9->setGeometry(QRect(10, 30, 321, 311));
        label_17 = new QLabel(greatestDistanceCenter);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(130, 10, 111, 16));
        stadiumList_9 = new QListWidget(greatestDistanceCenter);
        stadiumList_9->setObjectName(QString::fromUtf8("stadiumList_9"));
        stadiumList_9->setGeometry(QRect(330, 30, 321, 311));
        label_27 = new QLabel(greatestDistanceCenter);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(450, 10, 111, 16));
        tabWidget->addTab(greatestDistanceCenter, QString());
        smallestDistanceCenter = new QWidget();
        smallestDistanceCenter->setObjectName(QString::fromUtf8("smallestDistanceCenter"));
        teamListWidget_10 = new QListWidget(smallestDistanceCenter);
        teamListWidget_10->setObjectName(QString::fromUtf8("teamListWidget_10"));
        teamListWidget_10->setGeometry(QRect(10, 30, 321, 311));
        label_18 = new QLabel(smallestDistanceCenter);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(130, 10, 111, 16));
        stadiumList_10 = new QListWidget(smallestDistanceCenter);
        stadiumList_10->setObjectName(QString::fromUtf8("stadiumList_10"));
        stadiumList_10->setGeometry(QRect(330, 30, 321, 311));
        label_28 = new QLabel(smallestDistanceCenter);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(450, 10, 111, 16));
        tabWidget->addTab(smallestDistanceCenter, QString());
        label_12 = new QLabel(informationPage);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(490, 80, 181, 16));
        userStackedWidget->addWidget(informationPage);
        viewStadiumsPage = new QWidget();
        viewStadiumsPage->setObjectName(QString::fromUtf8("viewStadiumsPage"));
        souvenirListWidget_2 = new QListWidget(viewStadiumsPage);
        souvenirListWidget_2->setObjectName(QString::fromUtf8("souvenirListWidget_2"));
        souvenirListWidget_2->setGeometry(QRect(900, 120, 191, 271));
        stadiumListWidget_2 = new QListWidget(viewStadiumsPage);
        stadiumListWidget_2->setObjectName(QString::fromUtf8("stadiumListWidget_2"));
        stadiumListWidget_2->setGeometry(QRect(20, 120, 451, 591));
        groupBox_2 = new QGroupBox(viewStadiumsPage);
        groupBox_2->setObjectName(QString::fromUtf8("groupBox_2"));
        groupBox_2->setGeometry(QRect(520, 420, 621, 291));
        capacityLabel_2 = new QLabel(groupBox_2);
        capacityLabel_2->setObjectName(QString::fromUtf8("capacityLabel_2"));
        capacityLabel_2->setGeometry(QRect(50, 40, 51, 16));
        typologyLabel_2 = new QLabel(groupBox_2);
        typologyLabel_2->setObjectName(QString::fromUtf8("typologyLabel_2"));
        typologyLabel_2->setGeometry(QRect(50, 130, 61, 16));
        distToCenterLineEdit_2 = new QLineEdit(groupBox_2);
        distToCenterLineEdit_2->setObjectName(QString::fromUtf8("distToCenterLineEdit_2"));
        distToCenterLineEdit_2->setGeometry(QRect(360, 170, 113, 20));
        roofTypeLabel_2 = new QLabel(groupBox_2);
        roofTypeLabel_2->setObjectName(QString::fromUtf8("roofTypeLabel_2"));
        roofTypeLabel_2->setGeometry(QRect(390, 40, 61, 16));
        surfaceLabel_2 = new QLabel(groupBox_2);
        surfaceLabel_2->setObjectName(QString::fromUtf8("surfaceLabel_2"));
        surfaceLabel_2->setGeometry(QRect(220, 40, 47, 13));
        capacityLineEdit_2 = new QLineEdit(groupBox_2);
        capacityLineEdit_2->setObjectName(QString::fromUtf8("capacityLineEdit_2"));
        capacityLineEdit_2->setGeometry(QRect(20, 80, 113, 20));
        roofTypeLineEdit_2 = new QLineEdit(groupBox_2);
        roofTypeLineEdit_2->setObjectName(QString::fromUtf8("roofTypeLineEdit_2"));
        roofTypeLineEdit_2->setGeometry(QRect(360, 80, 113, 20));
        surfaceLineEdit_2 = new QLineEdit(groupBox_2);
        surfaceLineEdit_2->setObjectName(QString::fromUtf8("surfaceLineEdit_2"));
        surfaceLineEdit_2->setGeometry(QRect(190, 80, 113, 20));
        dateOpenedLineEdit_2 = new QLineEdit(groupBox_2);
        dateOpenedLineEdit_2->setObjectName(QString::fromUtf8("dateOpenedLineEdit_2"));
        dateOpenedLineEdit_2->setGeometry(QRect(190, 170, 113, 20));
        dateLabel_2 = new QLabel(groupBox_2);
        dateLabel_2->setObjectName(QString::fromUtf8("dateLabel_2"));
        dateLabel_2->setGeometry(QRect(210, 130, 81, 16));
        typologyLineEdit_2 = new QLineEdit(groupBox_2);
        typologyLineEdit_2->setObjectName(QString::fromUtf8("typologyLineEdit_2"));
        typologyLineEdit_2->setGeometry(QRect(20, 170, 113, 20));
        distToCenterLabel_2 = new QLabel(groupBox_2);
        distToCenterLabel_2->setObjectName(QString::fromUtf8("distToCenterLabel_2"));
        distToCenterLabel_2->setGeometry(QRect(360, 130, 131, 16));
        newLocationLineEdit_2 = new QLineEdit(groupBox_2);
        newLocationLineEdit_2->setObjectName(QString::fromUtf8("newLocationLineEdit_2"));
        newLocationLineEdit_2->setGeometry(QRect(20, 260, 113, 20));
        newLocationLabel_2 = new QLabel(groupBox_2);
        newLocationLabel_2->setObjectName(QString::fromUtf8("newLocationLabel_2"));
        newLocationLabel_2->setGeometry(QRect(40, 230, 81, 16));
        label_13 = new QLabel(viewStadiumsPage);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(980, 90, 61, 16));
        viewStadiumsBackButton = new QPushButton(viewStadiumsPage);
        viewStadiumsBackButton->setObjectName(QString::fromUtf8("viewStadiumsBackButton"));
        viewStadiumsBackButton->setGeometry(QRect(20, 20, 121, 41));
        souvenirPriceListWidget_2 = new QListWidget(viewStadiumsPage);
        souvenirPriceListWidget_2->setObjectName(QString::fromUtf8("souvenirPriceListWidget_2"));
        souvenirPriceListWidget_2->setGeometry(QRect(1090, 120, 51, 271));
        label_14 = new QLabel(viewStadiumsPage);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(210, 90, 51, 16));
        userStackedWidget->addWidget(viewStadiumsPage);
        primaryPageStackedWidget->addWidget(userPage);
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QString::fromUtf8("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1200, 21));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QString::fromUtf8("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QString::fromUtf8("statusBar"));
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        primaryPageStackedWidget->setCurrentIndex(2);
        tabWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", nullptr));
        loginPushButton->setText(QApplication::translate("MainWindow", "Login", nullptr));
        label->setText(QApplication::translate("MainWindow", "Ballgame Boogaloo", nullptr));
        label_2->setText(QApplication::translate("MainWindow", "Welcome", nullptr));
        usernameLabel->setText(QApplication::translate("MainWindow", "Username", nullptr));
        passwordLabel->setText(QApplication::translate("MainWindow", "Password", nullptr));
        welcomeLabel_admin->setText(QApplication::translate("MainWindow", "Welcome Admin", nullptr));
        informationButton_admin->setText(QApplication::translate("MainWindow", "View Stadiums", nullptr));
        takeTripButton_admin->setText(QApplication::translate("MainWindow", "Take a Trip", nullptr));
        manageStadiumsButton->setText(QApplication::translate("MainWindow", "Manage Stadiums", nullptr));
        label_3->setText(QApplication::translate("MainWindow", "Stadium", nullptr));
        label_10->setText(QApplication::translate("MainWindow", "Souvenirs", nullptr));
        manageStadiumsBackButton->setText(QApplication::translate("MainWindow", "Back", nullptr));
        groupBox->setTitle(QApplication::translate("MainWindow", "Stadium Attributes", nullptr));
        capacityLabel->setText(QApplication::translate("MainWindow", "Capacity", nullptr));
        typologyLabel->setText(QApplication::translate("MainWindow", "Typology", nullptr));
        roofTypeLabel->setText(QApplication::translate("MainWindow", "Roof Type", nullptr));
        surfaceLabel->setText(QApplication::translate("MainWindow", "Surface", nullptr));
        dateLabel->setText(QApplication::translate("MainWindow", "Date Opened", nullptr));
        distToCenterLabel->setText(QApplication::translate("MainWindow", "Dist. to Center Field", nullptr));
        newLocationLabel->setText(QApplication::translate("MainWindow", "New Location", nullptr));
        takeTripButton_user->setText(QApplication::translate("MainWindow", "View Stadiums", nullptr));
        informationButton_user->setText(QApplication::translate("MainWindow", "Information", nullptr));
        label_11->setText(QApplication::translate("MainWindow", "Welcome Regular User", nullptr));
        viewStadiumsButton->setText(QApplication::translate("MainWindow", "View Stadiums", nullptr));
        informationBackButton->setText(QApplication::translate("MainWindow", "Back", nullptr));
        label_5->setText(QApplication::translate("MainWindow", "Team Name", nullptr));
        label_19->setText(QApplication::translate("MainWindow", "Stadium Name", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(MajorLeagueTeam), QApplication::translate("MainWindow", "American-Name", nullptr));
        label_6->setText(QApplication::translate("MainWindow", "Team Name", nullptr));
        label_20->setText(QApplication::translate("MainWindow", "Stadium Name", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(MajorLeagueStadium), QApplication::translate("MainWindow", "American-Stadium", nullptr));
        label_7->setText(QApplication::translate("MainWindow", "Team Name", nullptr));
        label_21->setText(QApplication::translate("MainWindow", "Stadium Name", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(AmericanLeagueTeam), QApplication::translate("MainWindow", "National-Name", nullptr));
        label_4->setText(QApplication::translate("MainWindow", "Team Name", nullptr));
        label_22->setText(QApplication::translate("MainWindow", "Stadium Name", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(NationalLeagueStadium), QApplication::translate("MainWindow", "National-Stadium", nullptr));
        label_8->setText(QApplication::translate("MainWindow", "Team Name", nullptr));
        label_23->setText(QApplication::translate("MainWindow", "Stadium Name", nullptr));
        label_29->setText(QApplication::translate("MainWindow", "Park Typology", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(typology), QApplication::translate("MainWindow", "Park Typology", nullptr));
        label_9->setText(QApplication::translate("MainWindow", "Team Name", nullptr));
        label_24->setText(QApplication::translate("MainWindow", "Stadium Name", nullptr));
        label_30->setText(QApplication::translate("MainWindow", "Roof Type", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(openRoofType), QApplication::translate("MainWindow", "Roof Type", nullptr));
        label_15->setText(QApplication::translate("MainWindow", "Team Name", nullptr));
        label_25->setText(QApplication::translate("MainWindow", "Stadium Name", nullptr));
        label_31->setText(QApplication::translate("MainWindow", "Date Opened", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(dateOpened), QApplication::translate("MainWindow", "Date", nullptr));
        label_16->setText(QApplication::translate("MainWindow", "Team Name", nullptr));
        label_26->setText(QApplication::translate("MainWindow", "Stadium Name", nullptr));
        label_32->setText(QApplication::translate("MainWindow", "Stadium Seating Capacity", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(seatingCapacity), QApplication::translate("MainWindow", "Seating Capacity", nullptr));
        label_17->setText(QApplication::translate("MainWindow", "Team Name", nullptr));
        label_27->setText(QApplication::translate("MainWindow", "Stadium Name", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(greatestDistanceCenter), QApplication::translate("MainWindow", "Tab 2", nullptr));
        label_18->setText(QApplication::translate("MainWindow", "Team Name", nullptr));
        label_28->setText(QApplication::translate("MainWindow", "Stadium Name", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(smallestDistanceCenter), QApplication::translate("MainWindow", "Page", nullptr));
        label_12->setText(QApplication::translate("MainWindow", "View Information by Category", nullptr));
        groupBox_2->setTitle(QApplication::translate("MainWindow", "Stadium Attributes", nullptr));
        capacityLabel_2->setText(QApplication::translate("MainWindow", "Capacity", nullptr));
        typologyLabel_2->setText(QApplication::translate("MainWindow", "Typology", nullptr));
        roofTypeLabel_2->setText(QApplication::translate("MainWindow", "Roof Type", nullptr));
        surfaceLabel_2->setText(QApplication::translate("MainWindow", "Surface", nullptr));
        dateLabel_2->setText(QApplication::translate("MainWindow", "Date Opened", nullptr));
        distToCenterLabel_2->setText(QApplication::translate("MainWindow", "Dist. to Center Field", nullptr));
        newLocationLabel_2->setText(QApplication::translate("MainWindow", "New Location", nullptr));
        label_13->setText(QApplication::translate("MainWindow", "Souvenirs", nullptr));
        viewStadiumsBackButton->setText(QApplication::translate("MainWindow", "Back", nullptr));
        label_14->setText(QApplication::translate("MainWindow", "Stadium", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
