/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.12.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QListWidget>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *actionLogout;
    QWidget *centralWidget;
    QStackedWidget *primaryPageStackedWidget;
    QWidget *loginPage;
    QLabel *label;
    QLabel *label_2;
    QWidget *layoutWidget;
    QHBoxLayout *horizontalLayout_2;
    QLabel *usernameLabel;
    QLineEdit *usernameLineEdit;
    QWidget *layoutWidget1;
    QHBoxLayout *horizontalLayout;
    QLabel *passwordLabel;
    QLineEdit *passwordLineEdit;
    QCheckBox *checkBox_showPW;
    QPushButton *loginPushButton;
    QLabel *label_29;
    QWidget *adminPage;
    QStackedWidget *adminStackedWidget;
    QWidget *welcomePage_admin;
    QLabel *welcomeLabel_admin;
    QPushButton *informationButton_admin;
    QPushButton *takeTripButton_admin;
    QPushButton *manageStadiumsButton;
    QLabel *AlayoLogoLabel;
    QWidget *manageStadiumsPage;
    QListWidget *stadiumListWidget;
    QListWidget *souvenirListWidget;
    QLabel *label_3;
    QLabel *label_10;
    QPushButton *manageStadiumsBackButton;
    QGroupBox *groupBox;
    QLabel *capacityLabel;
    QLabel *typologyLabel;
    QLineEdit *distToCenterLineEdit;
    QLabel *roofTypeLabel;
    QLabel *surfaceLabel;
    QLineEdit *capacityLineEdit;
    QLineEdit *roofTypeLineEdit;
    QLineEdit *surfaceLineEdit;
    QLineEdit *dateOpenedLineEdit;
    QLabel *dateLabel;
    QLineEdit *typologyLineEdit;
    QLabel *distToCenterLabel;
    QLineEdit *stadiumLineEdit;
    QLabel *newStadiumLabel;
    QLineEdit *locationLineEdit;
    QLabel *locationLabel;
    QLineEdit *leagueLineEdit;
    QLabel *leagueLabel;
    QListWidget *souvenirPriceListWidget;
    QLineEdit *changeSouvenirPriceLineEdit;
    QLabel *changeSouvenirLabel;
    QLabel *changeSouvenirLabel_2;
    QLineEdit *souvenirAddItemNameTextEdit;
    QLineEdit *souvenirAddItemPriceTextEdit;
    QCheckBox *souvenirAddAllTeamsCheckbox;
    QPushButton *addSouvenirPushButton;
    QLabel *souvenirAddItemNameLabel;
    QLabel *souvenirAddItemPriceLabel;
    QPushButton *deleteSouvenirPushButton;
    QLineEdit *changeSouvenirNameLineEdit;
    QLabel *souvenirChangingName;
    QPushButton *changeSouvenirPushButton;
    QLabel *changeSouvenirLabel_3;
    QLabel *changeSouvenirLabel_4;
    QCheckBox *souvenirChangeAllTeamsCheckbox;
    QCheckBox *souvenirDeleteAllTeamsCheckbox;
    QPushButton *AddTeamButton;
    QPushButton *ReinitializeButton;
    QWidget *userPage;
    QStackedWidget *userStackedWidget;
    QWidget *welcomePage_user;
    QPushButton *takeTripButton_user;
    QPushButton *informationButton_user;
    QPushButton *viewStadiumsButton;
    QLabel *welcomeLabel_admin_2;
    QLabel *AlayoLogoLabel_2;
    QWidget *takeTripPage;
    QStackedWidget *takeTripStackedWidget;
    QWidget *tripTypeSelectionPage;
    QPushButton *visitSingleButton;
    QPushButton *visitMultipleButton;
    QLabel *TakeATripLabel;
    QPushButton *takeTripPageBackButton;
    QPushButton *performdfsButton;
    QPushButton *performbfsButton;
    QPushButton *performmstButton;
    QLabel *MLBImageLabel;
    QWidget *multipleSelectionPage;
    QListWidget *availibleStadiumsListWidget;
    QLabel *label_30;
    QPushButton *optimizeButton;
    QPushButton *goButton;
    QListWidget *selectedStadiumsListWidget;
    QPushButton *multipleSelectionPageBackButton;
    QCheckBox *selectAllTeamsCheckBox;
    QWidget *singleSelectionPage;
    QPushButton *singleSelectionPageBackButton;
    QWidget *onTripPage;
    QWidget *recieptPage;
    QLabel *label_11;
    QLineEdit *totalTripDistanceLineEdit;
    QWidget *dfsPage;
    QListWidget *dfsStadiumsListWidget;
    QPushButton *dfsPageBackButton;
    QLabel *dfsChooseStartingStadiumLabel;
    QLabel *dfsStartingStadiumLabel;
    QLineEdit *startingStadiumLineEdit;
    QPushButton *dfsPushButton;
    QListWidget *dfsResultsListWidget;
    QLabel *dfsTotalDistanceTraveledLabel;
    QLineEdit *dfsTotalDistanceTraveledLineEdit;
    QWidget *bfsPage;
    QLabel *bfsTotalDistanceTraveled;
    QListWidget *bfsResultsListWidget;
    QPushButton *bfsPushButton;
    QLineEdit *bfsStartingStadiumLineEdit;
    QLineEdit *bfsTotalDistanceTraveledLineEdit;
    QPushButton *bfsPageBackButton;
    QLabel *bfsStartingStadiumLabel;
    QListWidget *bfsStadiumListWidget;
    QLabel *bfsChooseStartingStadiumLabel;
    QWidget *mstPage;
    QPushButton *mstBackButton;
    QLabel *mstChooseStartingStadiumLabel;
    QLabel *mstStartingStadiumLabel;
    QLabel *mstTotalDistanceTraveled_2;
    QListWidget *mstResultsListWidget;
    QPushButton *mstPushButton;
    QLineEdit *mstStartingStadiumLineEdit;
    QListWidget *mstStadiumListWidget;
    QLineEdit *mstTotalDistanceTraveledLineEdit;
    QWidget *informationPage;
    QPushButton *informationBackButton;
    QTabWidget *tabWidget;
    QWidget *MajorLeagueTeam;
    QLabel *label_5;
    QLabel *label_19;
    QTableWidget *teamTableWidget_1;
    QWidget *MajorLeagueStadium;
    QLabel *label_6;
    QLabel *label_20;
    QTableWidget *teamTableWidget_2;
    QWidget *AmericanLeagueTeam;
    QLabel *label_7;
    QLabel *label_21;
    QTableWidget *teamTableWidget_3;
    QWidget *NationalLeagueStadium;
    QLabel *label_4;
    QLabel *label_22;
    QTableWidget *teamTableWidget_4;
    QWidget *typology;
    QLabel *label_8;
    QLabel *label_23;
    QTableWidget *teamTableWidget_5;
    QWidget *openRoofType;
    QLabel *label_9;
    QLabel *label_24;
    QTableWidget *teamTableWidget_6;
    QWidget *dateOpened;
    QLabel *label_15;
    QLabel *label_25;
    QTableWidget *teamTableWidget_7;
    QWidget *seatingCapacity;
    QLabel *label_16;
    QLabel *label_26;
    QTableWidget *teamTableWidget_8;
    QLabel *label_31;
    QLabel *label_32;
    QWidget *greatestDistanceCenter;
    QTableWidget *teamTableWidget_9;
    QLabel *label_17;
    QLabel *label_27;
    QWidget *smallestDistanceCenter;
    QLabel *label_18;
    QLabel *label_28;
    QTableWidget *teamTableWidget_10;
    QLabel *label_12;
    QWidget *viewStadiumsPage;
    QListWidget *souvenirListWidget_2;
    QListWidget *stadiumListWidget_2;
    QGroupBox *groupBox_2;
    QLabel *capacityLabel_2;
    QLabel *typologyLabel_2;
    QLineEdit *distToCenterLineEdit_2;
    QLabel *roofTypeLabel_2;
    QLabel *surfaceLabel_2;
    QLineEdit *capacityLineEdit_2;
    QLineEdit *roofTypeLineEdit_2;
    QLineEdit *surfaceLineEdit_2;
    QLineEdit *dateOpenedLineEdit_2;
    QLabel *dateLabel_2;
    QLineEdit *typologyLineEdit_2;
    QLabel *distToCenterLabel_2;
    QLineEdit *locationLineEdit_2;
    QLabel *locationLabel_2;
    QLineEdit *leagueLineEdit_2;
    QLabel *leagueLabel_2;
    QLabel *label_13;
    QPushButton *viewStadiumsBackButton;
    QListWidget *souvenirPriceListWidget_2;
    QLabel *label_14;
    QMenuBar *menuBar;
    QMenu *menuFile;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1200, 800);
        QSizePolicy sizePolicy(QSizePolicy::Fixed, QSizePolicy::Fixed);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(MainWindow->sizePolicy().hasHeightForWidth());
        MainWindow->setSizePolicy(sizePolicy);
        MainWindow->setMinimumSize(QSize(1200, 800));
        MainWindow->setMaximumSize(QSize(1200, 800));
        MainWindow->setBaseSize(QSize(1000, 700));
        QPalette palette;
        QBrush brush(QColor(0, 0, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(0, 196, 255, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        QBrush brush2(QColor(127, 226, 255, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Light, brush2);
        QBrush brush3(QColor(63, 211, 255, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        QBrush brush4(QColor(0, 98, 127, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush4);
        QBrush brush5(QColor(0, 131, 170, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        QBrush brush6(QColor(255, 255, 255, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush);
        QBrush brush7(QColor(127, 225, 255, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush7);
        QBrush brush8(QColor(255, 255, 220, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        QBrush brush9(QColor(0, 0, 0, 128));
        brush9.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::PlaceholderText, brush9);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush7);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush9);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush9);
        MainWindow->setPalette(palette);
        QFont font;
        font.setPointSize(10);
        MainWindow->setFont(font);
        actionLogout = new QAction(MainWindow);
        actionLogout->setObjectName(QString::fromUtf8("actionLogout"));
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette1.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette1.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette1.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush);
        palette1.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Active, QPalette::AlternateBase, brush7);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette1.setBrush(QPalette::Active, QPalette::PlaceholderText, brush9);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette1.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette1.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush7);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush9);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush9);
        centralWidget->setPalette(palette1);
        primaryPageStackedWidget = new QStackedWidget(centralWidget);
        primaryPageStackedWidget->setObjectName(QString::fromUtf8("primaryPageStackedWidget"));
        primaryPageStackedWidget->setGeometry(QRect(0, 40, 1201, 761));
        QSizePolicy sizePolicy1(QSizePolicy::Fixed, QSizePolicy::Preferred);
        sizePolicy1.setHorizontalStretch(0);
        sizePolicy1.setVerticalStretch(0);
        sizePolicy1.setHeightForWidth(primaryPageStackedWidget->sizePolicy().hasHeightForWidth());
        primaryPageStackedWidget->setSizePolicy(sizePolicy1);
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette2.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette2.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette2.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette2.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush);
        palette2.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette2.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Active, QPalette::AlternateBase, brush7);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette2.setBrush(QPalette::Active, QPalette::PlaceholderText, brush9);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette2.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette2.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush7);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush9);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette2.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette2.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette2.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette2.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush9);
        primaryPageStackedWidget->setPalette(palette2);
        loginPage = new QWidget();
        loginPage->setObjectName(QString::fromUtf8("loginPage"));
        label = new QLabel(loginPage);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(370, 50, 471, 131));
        QFont font1;
        font1.setPointSize(36);
        font1.setBold(true);
        font1.setWeight(75);
        label->setFont(font1);
        label_2 = new QLabel(loginPage);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(550, 260, 91, 31));
        layoutWidget = new QWidget(loginPage);
        layoutWidget->setObjectName(QString::fromUtf8("layoutWidget"));
        layoutWidget->setGeometry(QRect(490, 310, 191, 26));
        horizontalLayout_2 = new QHBoxLayout(layoutWidget);
        horizontalLayout_2->setSpacing(6);
        horizontalLayout_2->setContentsMargins(11, 11, 11, 11);
        horizontalLayout_2->setObjectName(QString::fromUtf8("horizontalLayout_2"));
        horizontalLayout_2->setContentsMargins(0, 0, 0, 0);
        usernameLabel = new QLabel(layoutWidget);
        usernameLabel->setObjectName(QString::fromUtf8("usernameLabel"));

        horizontalLayout_2->addWidget(usernameLabel);

        usernameLineEdit = new QLineEdit(layoutWidget);
        usernameLineEdit->setObjectName(QString::fromUtf8("usernameLineEdit"));

        horizontalLayout_2->addWidget(usernameLineEdit);

        layoutWidget1 = new QWidget(loginPage);
        layoutWidget1->setObjectName(QString::fromUtf8("layoutWidget1"));
        layoutWidget1->setGeometry(QRect(490, 350, 191, 26));
        horizontalLayout = new QHBoxLayout(layoutWidget1);
        horizontalLayout->setSpacing(6);
        horizontalLayout->setContentsMargins(11, 11, 11, 11);
        horizontalLayout->setObjectName(QString::fromUtf8("horizontalLayout"));
        horizontalLayout->setContentsMargins(0, 0, 0, 0);
        passwordLabel = new QLabel(layoutWidget1);
        passwordLabel->setObjectName(QString::fromUtf8("passwordLabel"));

        horizontalLayout->addWidget(passwordLabel);

        passwordLineEdit = new QLineEdit(layoutWidget1);
        passwordLineEdit->setObjectName(QString::fromUtf8("passwordLineEdit"));
        passwordLineEdit->setEchoMode(QLineEdit::Password);

        horizontalLayout->addWidget(passwordLineEdit);

        checkBox_showPW = new QCheckBox(loginPage);
        checkBox_showPW->setObjectName(QString::fromUtf8("checkBox_showPW"));
        checkBox_showPW->setGeometry(QRect(710, 356, 91, 21));
        loginPushButton = new QPushButton(loginPage);
        loginPushButton->setObjectName(QString::fromUtf8("loginPushButton"));
        loginPushButton->setGeometry(QRect(490, 390, 191, 41));
        label_29 = new QLabel(loginPage);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(550, 160, 101, 71));
        QFont font2;
        font2.setFamily(QString::fromUtf8("Freestyle Script"));
        font2.setPointSize(36);
        label_29->setFont(font2);
        primaryPageStackedWidget->addWidget(loginPage);
        adminPage = new QWidget();
        adminPage->setObjectName(QString::fromUtf8("adminPage"));
        adminStackedWidget = new QStackedWidget(adminPage);
        adminStackedWidget->setObjectName(QString::fromUtf8("adminStackedWidget"));
        adminStackedWidget->setGeometry(QRect(-10, -30, 1201, 771));
        welcomePage_admin = new QWidget();
        welcomePage_admin->setObjectName(QString::fromUtf8("welcomePage_admin"));
        welcomeLabel_admin = new QLabel(welcomePage_admin);
        welcomeLabel_admin->setObjectName(QString::fromUtf8("welcomeLabel_admin"));
        welcomeLabel_admin->setGeometry(QRect(520, 30, 181, 31));
        QFont font3;
        font3.setPointSize(16);
        font3.setBold(true);
        font3.setWeight(75);
        welcomeLabel_admin->setFont(font3);
        informationButton_admin = new QPushButton(welcomePage_admin);
        informationButton_admin->setObjectName(QString::fromUtf8("informationButton_admin"));
        informationButton_admin->setGeometry(QRect(470, 510, 291, 61));
        takeTripButton_admin = new QPushButton(welcomePage_admin);
        takeTripButton_admin->setObjectName(QString::fromUtf8("takeTripButton_admin"));
        takeTripButton_admin->setGeometry(QRect(60, 510, 301, 61));
        sizePolicy.setHeightForWidth(takeTripButton_admin->sizePolicy().hasHeightForWidth());
        takeTripButton_admin->setSizePolicy(sizePolicy);
        manageStadiumsButton = new QPushButton(welcomePage_admin);
        manageStadiumsButton->setObjectName(QString::fromUtf8("manageStadiumsButton"));
        manageStadiumsButton->setGeometry(QRect(860, 510, 291, 61));
        sizePolicy.setHeightForWidth(manageStadiumsButton->sizePolicy().hasHeightForWidth());
        manageStadiumsButton->setSizePolicy(sizePolicy);
        AlayoLogoLabel = new QLabel(welcomePage_admin);
        AlayoLogoLabel->setObjectName(QString::fromUtf8("AlayoLogoLabel"));
        AlayoLogoLabel->setGeometry(QRect(380, 90, 461, 381));
        adminStackedWidget->addWidget(welcomePage_admin);
        manageStadiumsPage = new QWidget();
        manageStadiumsPage->setObjectName(QString::fromUtf8("manageStadiumsPage"));
        stadiumListWidget = new QListWidget(manageStadiumsPage);
        stadiumListWidget->setObjectName(QString::fromUtf8("stadiumListWidget"));
        stadiumListWidget->setGeometry(QRect(40, 120, 451, 591));
        souvenirListWidget = new QListWidget(manageStadiumsPage);
        souvenirListWidget->setObjectName(QString::fromUtf8("souvenirListWidget"));
        souvenirListWidget->setGeometry(QRect(850, 60, 191, 251));
        label_3 = new QLabel(manageStadiumsPage);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(230, 80, 81, 31));
        label_3->setFont(font3);
        label_10 = new QLabel(manageStadiumsPage);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(1000, 30, 61, 16));
        manageStadiumsBackButton = new QPushButton(manageStadiumsPage);
        manageStadiumsBackButton->setObjectName(QString::fromUtf8("manageStadiumsBackButton"));
        manageStadiumsBackButton->setGeometry(QRect(40, 30, 121, 41));
        groupBox = new QGroupBox(manageStadiumsPage);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(590, 410, 501, 301));
        capacityLabel = new QLabel(groupBox);
        capacityLabel->setObjectName(QString::fromUtf8("capacityLabel"));
        capacityLabel->setGeometry(QRect(50, 30, 51, 16));
        typologyLabel = new QLabel(groupBox);
        typologyLabel->setObjectName(QString::fromUtf8("typologyLabel"));
        typologyLabel->setGeometry(QRect(50, 120, 61, 16));
        distToCenterLineEdit = new QLineEdit(groupBox);
        distToCenterLineEdit->setObjectName(QString::fromUtf8("distToCenterLineEdit"));
        distToCenterLineEdit->setGeometry(QRect(360, 150, 113, 20));
        roofTypeLabel = new QLabel(groupBox);
        roofTypeLabel->setObjectName(QString::fromUtf8("roofTypeLabel"));
        roofTypeLabel->setGeometry(QRect(390, 30, 61, 16));
        surfaceLabel = new QLabel(groupBox);
        surfaceLabel->setObjectName(QString::fromUtf8("surfaceLabel"));
        surfaceLabel->setGeometry(QRect(220, 30, 47, 13));
        capacityLineEdit = new QLineEdit(groupBox);
        capacityLineEdit->setObjectName(QString::fromUtf8("capacityLineEdit"));
        capacityLineEdit->setGeometry(QRect(20, 60, 113, 20));
        roofTypeLineEdit = new QLineEdit(groupBox);
        roofTypeLineEdit->setObjectName(QString::fromUtf8("roofTypeLineEdit"));
        roofTypeLineEdit->setGeometry(QRect(360, 60, 113, 20));
        surfaceLineEdit = new QLineEdit(groupBox);
        surfaceLineEdit->setObjectName(QString::fromUtf8("surfaceLineEdit"));
        surfaceLineEdit->setGeometry(QRect(190, 60, 113, 20));
        dateOpenedLineEdit = new QLineEdit(groupBox);
        dateOpenedLineEdit->setObjectName(QString::fromUtf8("dateOpenedLineEdit"));
        dateOpenedLineEdit->setGeometry(QRect(190, 150, 113, 20));
        dateLabel = new QLabel(groupBox);
        dateLabel->setObjectName(QString::fromUtf8("dateLabel"));
        dateLabel->setGeometry(QRect(210, 120, 81, 16));
        typologyLineEdit = new QLineEdit(groupBox);
        typologyLineEdit->setObjectName(QString::fromUtf8("typologyLineEdit"));
        typologyLineEdit->setGeometry(QRect(20, 150, 113, 20));
        distToCenterLabel = new QLabel(groupBox);
        distToCenterLabel->setObjectName(QString::fromUtf8("distToCenterLabel"));
        distToCenterLabel->setGeometry(QRect(360, 120, 131, 16));
        stadiumLineEdit = new QLineEdit(groupBox);
        stadiumLineEdit->setObjectName(QString::fromUtf8("stadiumLineEdit"));
        stadiumLineEdit->setGeometry(QRect(20, 240, 113, 20));
        newStadiumLabel = new QLabel(groupBox);
        newStadiumLabel->setObjectName(QString::fromUtf8("newStadiumLabel"));
        newStadiumLabel->setGeometry(QRect(50, 210, 81, 16));
        locationLineEdit = new QLineEdit(groupBox);
        locationLineEdit->setObjectName(QString::fromUtf8("locationLineEdit"));
        locationLineEdit->setGeometry(QRect(172, 240, 161, 20));
        locationLabel = new QLabel(groupBox);
        locationLabel->setObjectName(QString::fromUtf8("locationLabel"));
        locationLabel->setGeometry(QRect(230, 210, 81, 16));
        leagueLineEdit = new QLineEdit(groupBox);
        leagueLineEdit->setObjectName(QString::fromUtf8("leagueLineEdit"));
        leagueLineEdit->setGeometry(QRect(360, 240, 113, 20));
        leagueLabel = new QLabel(groupBox);
        leagueLabel->setObjectName(QString::fromUtf8("leagueLabel"));
        leagueLabel->setGeometry(QRect(400, 210, 81, 16));
        souvenirPriceListWidget = new QListWidget(manageStadiumsPage);
        souvenirPriceListWidget->setObjectName(QString::fromUtf8("souvenirPriceListWidget"));
        souvenirPriceListWidget->setGeometry(QRect(1040, 60, 51, 251));
        changeSouvenirPriceLineEdit = new QLineEdit(manageStadiumsPage);
        changeSouvenirPriceLineEdit->setObjectName(QString::fromUtf8("changeSouvenirPriceLineEdit"));
        changeSouvenirPriceLineEdit->setGeometry(QRect(850, 370, 113, 20));
        changeSouvenirLabel = new QLabel(manageStadiumsPage);
        changeSouvenirLabel->setObjectName(QString::fromUtf8("changeSouvenirLabel"));
        changeSouvenirLabel->setGeometry(QRect(850, 320, 111, 16));
        changeSouvenirLabel_2 = new QLabel(manageStadiumsPage);
        changeSouvenirLabel_2->setObjectName(QString::fromUtf8("changeSouvenirLabel_2"));
        changeSouvenirLabel_2->setGeometry(QRect(630, 170, 111, 16));
        souvenirAddItemNameTextEdit = new QLineEdit(manageStadiumsPage);
        souvenirAddItemNameTextEdit->setObjectName(QString::fromUtf8("souvenirAddItemNameTextEdit"));
        souvenirAddItemNameTextEdit->setGeometry(QRect(610, 200, 113, 20));
        souvenirAddItemPriceTextEdit = new QLineEdit(manageStadiumsPage);
        souvenirAddItemPriceTextEdit->setObjectName(QString::fromUtf8("souvenirAddItemPriceTextEdit"));
        souvenirAddItemPriceTextEdit->setGeometry(QRect(610, 230, 113, 20));
        souvenirAddAllTeamsCheckbox = new QCheckBox(manageStadiumsPage);
        souvenirAddAllTeamsCheckbox->setObjectName(QString::fromUtf8("souvenirAddAllTeamsCheckbox"));
        souvenirAddAllTeamsCheckbox->setGeometry(QRect(690, 260, 81, 17));
        addSouvenirPushButton = new QPushButton(manageStadiumsPage);
        addSouvenirPushButton->setObjectName(QString::fromUtf8("addSouvenirPushButton"));
        addSouvenirPushButton->setGeometry(QRect(610, 260, 61, 31));
        souvenirAddItemNameLabel = new QLabel(manageStadiumsPage);
        souvenirAddItemNameLabel->setObjectName(QString::fromUtf8("souvenirAddItemNameLabel"));
        souvenirAddItemNameLabel->setGeometry(QRect(730, 200, 111, 16));
        souvenirAddItemPriceLabel = new QLabel(manageStadiumsPage);
        souvenirAddItemPriceLabel->setObjectName(QString::fromUtf8("souvenirAddItemPriceLabel"));
        souvenirAddItemPriceLabel->setGeometry(QRect(730, 230, 111, 16));
        deleteSouvenirPushButton = new QPushButton(manageStadiumsPage);
        deleteSouvenirPushButton->setObjectName(QString::fromUtf8("deleteSouvenirPushButton"));
        deleteSouvenirPushButton->setGeometry(QRect(1100, 70, 101, 41));
        changeSouvenirNameLineEdit = new QLineEdit(manageStadiumsPage);
        changeSouvenirNameLineEdit->setObjectName(QString::fromUtf8("changeSouvenirNameLineEdit"));
        changeSouvenirNameLineEdit->setGeometry(QRect(850, 340, 113, 20));
        souvenirChangingName = new QLabel(manageStadiumsPage);
        souvenirChangingName->setObjectName(QString::fromUtf8("souvenirChangingName"));
        souvenirChangingName->setGeometry(QRect(970, 320, 181, 16));
        changeSouvenirPushButton = new QPushButton(manageStadiumsPage);
        changeSouvenirPushButton->setObjectName(QString::fromUtf8("changeSouvenirPushButton"));
        changeSouvenirPushButton->setGeometry(QRect(980, 340, 111, 41));
        changeSouvenirLabel_3 = new QLabel(manageStadiumsPage);
        changeSouvenirLabel_3->setObjectName(QString::fromUtf8("changeSouvenirLabel_3"));
        changeSouvenirLabel_3->setGeometry(QRect(800, 340, 41, 16));
        changeSouvenirLabel_4 = new QLabel(manageStadiumsPage);
        changeSouvenirLabel_4->setObjectName(QString::fromUtf8("changeSouvenirLabel_4"));
        changeSouvenirLabel_4->setGeometry(QRect(800, 370, 41, 16));
        souvenirChangeAllTeamsCheckbox = new QCheckBox(manageStadiumsPage);
        souvenirChangeAllTeamsCheckbox->setObjectName(QString::fromUtf8("souvenirChangeAllTeamsCheckbox"));
        souvenirChangeAllTeamsCheckbox->setGeometry(QRect(990, 390, 81, 17));
        souvenirDeleteAllTeamsCheckbox = new QCheckBox(manageStadiumsPage);
        souvenirDeleteAllTeamsCheckbox->setObjectName(QString::fromUtf8("souvenirDeleteAllTeamsCheckbox"));
        souvenirDeleteAllTeamsCheckbox->setGeometry(QRect(1110, 120, 81, 17));
        AddTeamButton = new QPushButton(manageStadiumsPage);
        AddTeamButton->setObjectName(QString::fromUtf8("AddTeamButton"));
        AddTeamButton->setGeometry(QRect(1100, 490, 101, 41));
        ReinitializeButton = new QPushButton(manageStadiumsPage);
        ReinitializeButton->setObjectName(QString::fromUtf8("ReinitializeButton"));
        ReinitializeButton->setGeometry(QRect(1100, 560, 101, 41));
        adminStackedWidget->addWidget(manageStadiumsPage);
        primaryPageStackedWidget->addWidget(adminPage);
        userPage = new QWidget();
        userPage->setObjectName(QString::fromUtf8("userPage"));
        userStackedWidget = new QStackedWidget(userPage);
        userStackedWidget->setObjectName(QString::fromUtf8("userStackedWidget"));
        userStackedWidget->setGeometry(QRect(0, -20, 1201, 781));
        welcomePage_user = new QWidget();
        welcomePage_user->setObjectName(QString::fromUtf8("welcomePage_user"));
        takeTripButton_user = new QPushButton(welcomePage_user);
        takeTripButton_user->setObjectName(QString::fromUtf8("takeTripButton_user"));
        takeTripButton_user->setGeometry(QRect(50, 530, 301, 61));
        sizePolicy.setHeightForWidth(takeTripButton_user->sizePolicy().hasHeightForWidth());
        takeTripButton_user->setSizePolicy(sizePolicy);
        informationButton_user = new QPushButton(welcomePage_user);
        informationButton_user->setObjectName(QString::fromUtf8("informationButton_user"));
        informationButton_user->setGeometry(QRect(460, 530, 291, 61));
        viewStadiumsButton = new QPushButton(welcomePage_user);
        viewStadiumsButton->setObjectName(QString::fromUtf8("viewStadiumsButton"));
        viewStadiumsButton->setGeometry(QRect(850, 530, 291, 61));
        welcomeLabel_admin_2 = new QLabel(welcomePage_user);
        welcomeLabel_admin_2->setObjectName(QString::fromUtf8("welcomeLabel_admin_2"));
        welcomeLabel_admin_2->setGeometry(QRect(520, 50, 181, 31));
        welcomeLabel_admin_2->setFont(font3);
        AlayoLogoLabel_2 = new QLabel(welcomePage_user);
        AlayoLogoLabel_2->setObjectName(QString::fromUtf8("AlayoLogoLabel_2"));
        AlayoLogoLabel_2->setGeometry(QRect(370, 110, 461, 381));
        userStackedWidget->addWidget(welcomePage_user);
        takeTripPage = new QWidget();
        takeTripPage->setObjectName(QString::fromUtf8("takeTripPage"));
        takeTripStackedWidget = new QStackedWidget(takeTripPage);
        takeTripStackedWidget->setObjectName(QString::fromUtf8("takeTripStackedWidget"));
        takeTripStackedWidget->setGeometry(QRect(0, -30, 1191, 761));
        tripTypeSelectionPage = new QWidget();
        tripTypeSelectionPage->setObjectName(QString::fromUtf8("tripTypeSelectionPage"));
        visitSingleButton = new QPushButton(tripTypeSelectionPage);
        visitSingleButton->setObjectName(QString::fromUtf8("visitSingleButton"));
        visitSingleButton->setGeometry(QRect(260, 680, 331, 81));
        visitMultipleButton = new QPushButton(tripTypeSelectionPage);
        visitMultipleButton->setObjectName(QString::fromUtf8("visitMultipleButton"));
        visitMultipleButton->setGeometry(QRect(600, 680, 331, 81));
        TakeATripLabel = new QLabel(tripTypeSelectionPage);
        TakeATripLabel->setObjectName(QString::fromUtf8("TakeATripLabel"));
        TakeATripLabel->setGeometry(QRect(520, 50, 151, 51));
        QFont font4;
        font4.setPointSize(20);
        font4.setBold(true);
        font4.setWeight(75);
        TakeATripLabel->setFont(font4);
        takeTripPageBackButton = new QPushButton(tripTypeSelectionPage);
        takeTripPageBackButton->setObjectName(QString::fromUtf8("takeTripPageBackButton"));
        takeTripPageBackButton->setGeometry(QRect(60, 50, 121, 41));
        performdfsButton = new QPushButton(tripTypeSelectionPage);
        performdfsButton->setObjectName(QString::fromUtf8("performdfsButton"));
        performdfsButton->setGeometry(QRect(90, 590, 331, 81));
        performbfsButton = new QPushButton(tripTypeSelectionPage);
        performbfsButton->setObjectName(QString::fromUtf8("performbfsButton"));
        performbfsButton->setGeometry(QRect(770, 590, 331, 81));
        performmstButton = new QPushButton(tripTypeSelectionPage);
        performmstButton->setObjectName(QString::fromUtf8("performmstButton"));
        performmstButton->setGeometry(QRect(430, 590, 331, 81));
        MLBImageLabel = new QLabel(tripTypeSelectionPage);
        MLBImageLabel->setObjectName(QString::fromUtf8("MLBImageLabel"));
        MLBImageLabel->setGeometry(QRect(136, 100, 921, 491));
        takeTripStackedWidget->addWidget(tripTypeSelectionPage);
        multipleSelectionPage = new QWidget();
        multipleSelectionPage->setObjectName(QString::fromUtf8("multipleSelectionPage"));
        availibleStadiumsListWidget = new QListWidget(multipleSelectionPage);
        availibleStadiumsListWidget->setObjectName(QString::fromUtf8("availibleStadiumsListWidget"));
        availibleStadiumsListWidget->setGeometry(QRect(60, 140, 371, 521));
        label_30 = new QLabel(multipleSelectionPage);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(180, 120, 61, 16));
        optimizeButton = new QPushButton(multipleSelectionPage);
        optimizeButton->setObjectName(QString::fromUtf8("optimizeButton"));
        optimizeButton->setGeometry(QRect(900, 450, 161, 71));
        goButton = new QPushButton(multipleSelectionPage);
        goButton->setObjectName(QString::fromUtf8("goButton"));
        goButton->setGeometry(QRect(900, 560, 161, 71));
        selectedStadiumsListWidget = new QListWidget(multipleSelectionPage);
        selectedStadiumsListWidget->setObjectName(QString::fromUtf8("selectedStadiumsListWidget"));
        selectedStadiumsListWidget->setGeometry(QRect(480, 140, 371, 521));
        multipleSelectionPageBackButton = new QPushButton(multipleSelectionPage);
        multipleSelectionPageBackButton->setObjectName(QString::fromUtf8("multipleSelectionPageBackButton"));
        multipleSelectionPageBackButton->setGeometry(QRect(60, 50, 121, 41));
        selectAllTeamsCheckBox = new QCheckBox(multipleSelectionPage);
        selectAllTeamsCheckBox->setObjectName(QString::fromUtf8("selectAllTeamsCheckBox"));
        selectAllTeamsCheckBox->setGeometry(QRect(210, 660, 161, 41));
        QFont font5;
        font5.setPointSize(12);
        selectAllTeamsCheckBox->setFont(font5);
        selectAllTeamsCheckBox->setIconSize(QSize(20, 20));
        takeTripStackedWidget->addWidget(multipleSelectionPage);
        singleSelectionPage = new QWidget();
        singleSelectionPage->setObjectName(QString::fromUtf8("singleSelectionPage"));
        singleSelectionPageBackButton = new QPushButton(singleSelectionPage);
        singleSelectionPageBackButton->setObjectName(QString::fromUtf8("singleSelectionPageBackButton"));
        singleSelectionPageBackButton->setGeometry(QRect(60, 50, 121, 41));
        takeTripStackedWidget->addWidget(singleSelectionPage);
        onTripPage = new QWidget();
        onTripPage->setObjectName(QString::fromUtf8("onTripPage"));
        takeTripStackedWidget->addWidget(onTripPage);
        recieptPage = new QWidget();
        recieptPage->setObjectName(QString::fromUtf8("recieptPage"));
        label_11 = new QLabel(recieptPage);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(460, 370, 241, 16));
        totalTripDistanceLineEdit = new QLineEdit(recieptPage);
        totalTripDistanceLineEdit->setObjectName(QString::fromUtf8("totalTripDistanceLineEdit"));
        totalTripDistanceLineEdit->setGeometry(QRect(450, 410, 241, 20));
        takeTripStackedWidget->addWidget(recieptPage);
        dfsPage = new QWidget();
        dfsPage->setObjectName(QString::fromUtf8("dfsPage"));
        dfsStadiumsListWidget = new QListWidget(dfsPage);
        dfsStadiumsListWidget->setObjectName(QString::fromUtf8("dfsStadiumsListWidget"));
        dfsStadiumsListWidget->setGeometry(QRect(210, 80, 291, 591));
        dfsPageBackButton = new QPushButton(dfsPage);
        dfsPageBackButton->setObjectName(QString::fromUtf8("dfsPageBackButton"));
        dfsPageBackButton->setGeometry(QRect(60, 50, 121, 41));
        dfsChooseStartingStadiumLabel = new QLabel(dfsPage);
        dfsChooseStartingStadiumLabel->setObjectName(QString::fromUtf8("dfsChooseStartingStadiumLabel"));
        dfsChooseStartingStadiumLabel->setGeometry(QRect(210, 55, 211, 21));
        dfsChooseStartingStadiumLabel->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        dfsStartingStadiumLabel = new QLabel(dfsPage);
        dfsStartingStadiumLabel->setObjectName(QString::fromUtf8("dfsStartingStadiumLabel"));
        dfsStartingStadiumLabel->setGeometry(QRect(740, 60, 121, 31));
        startingStadiumLineEdit = new QLineEdit(dfsPage);
        startingStadiumLineEdit->setObjectName(QString::fromUtf8("startingStadiumLineEdit"));
        startingStadiumLineEdit->setGeometry(QRect(640, 110, 321, 21));
        dfsPushButton = new QPushButton(dfsPage);
        dfsPushButton->setObjectName(QString::fromUtf8("dfsPushButton"));
        dfsPushButton->setGeometry(QRect(680, 160, 241, 61));
        dfsResultsListWidget = new QListWidget(dfsPage);
        dfsResultsListWidget->setObjectName(QString::fromUtf8("dfsResultsListWidget"));
        dfsResultsListWidget->setGeometry(QRect(670, 230, 256, 381));
        dfsTotalDistanceTraveledLabel = new QLabel(dfsPage);
        dfsTotalDistanceTraveledLabel->setObjectName(QString::fromUtf8("dfsTotalDistanceTraveledLabel"));
        dfsTotalDistanceTraveledLabel->setGeometry(QRect(670, 650, 141, 16));
        dfsTotalDistanceTraveledLineEdit = new QLineEdit(dfsPage);
        dfsTotalDistanceTraveledLineEdit->setObjectName(QString::fromUtf8("dfsTotalDistanceTraveledLineEdit"));
        dfsTotalDistanceTraveledLineEdit->setGeometry(QRect(830, 650, 113, 20));
        takeTripStackedWidget->addWidget(dfsPage);
        bfsPage = new QWidget();
        bfsPage->setObjectName(QString::fromUtf8("bfsPage"));
        bfsTotalDistanceTraveled = new QLabel(bfsPage);
        bfsTotalDistanceTraveled->setObjectName(QString::fromUtf8("bfsTotalDistanceTraveled"));
        bfsTotalDistanceTraveled->setGeometry(QRect(670, 650, 141, 16));
        bfsResultsListWidget = new QListWidget(bfsPage);
        bfsResultsListWidget->setObjectName(QString::fromUtf8("bfsResultsListWidget"));
        bfsResultsListWidget->setGeometry(QRect(670, 230, 256, 381));
        bfsPushButton = new QPushButton(bfsPage);
        bfsPushButton->setObjectName(QString::fromUtf8("bfsPushButton"));
        bfsPushButton->setGeometry(QRect(680, 160, 241, 61));
        bfsStartingStadiumLineEdit = new QLineEdit(bfsPage);
        bfsStartingStadiumLineEdit->setObjectName(QString::fromUtf8("bfsStartingStadiumLineEdit"));
        bfsStartingStadiumLineEdit->setGeometry(QRect(640, 110, 321, 21));
        bfsTotalDistanceTraveledLineEdit = new QLineEdit(bfsPage);
        bfsTotalDistanceTraveledLineEdit->setObjectName(QString::fromUtf8("bfsTotalDistanceTraveledLineEdit"));
        bfsTotalDistanceTraveledLineEdit->setGeometry(QRect(830, 650, 113, 20));
        bfsPageBackButton = new QPushButton(bfsPage);
        bfsPageBackButton->setObjectName(QString::fromUtf8("bfsPageBackButton"));
        bfsPageBackButton->setGeometry(QRect(60, 50, 121, 41));
        bfsStartingStadiumLabel = new QLabel(bfsPage);
        bfsStartingStadiumLabel->setObjectName(QString::fromUtf8("bfsStartingStadiumLabel"));
        bfsStartingStadiumLabel->setGeometry(QRect(740, 60, 121, 31));
        bfsStadiumListWidget = new QListWidget(bfsPage);
        bfsStadiumListWidget->setObjectName(QString::fromUtf8("bfsStadiumListWidget"));
        bfsStadiumListWidget->setGeometry(QRect(210, 80, 291, 591));
        bfsChooseStartingStadiumLabel = new QLabel(bfsPage);
        bfsChooseStartingStadiumLabel->setObjectName(QString::fromUtf8("bfsChooseStartingStadiumLabel"));
        bfsChooseStartingStadiumLabel->setGeometry(QRect(210, 55, 211, 21));
        bfsChooseStartingStadiumLabel->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        takeTripStackedWidget->addWidget(bfsPage);
        mstPage = new QWidget();
        mstPage->setObjectName(QString::fromUtf8("mstPage"));
        mstBackButton = new QPushButton(mstPage);
        mstBackButton->setObjectName(QString::fromUtf8("mstBackButton"));
        mstBackButton->setGeometry(QRect(60, 50, 121, 41));
        mstChooseStartingStadiumLabel = new QLabel(mstPage);
        mstChooseStartingStadiumLabel->setObjectName(QString::fromUtf8("mstChooseStartingStadiumLabel"));
        mstChooseStartingStadiumLabel->setGeometry(QRect(210, 55, 211, 21));
        mstChooseStartingStadiumLabel->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        mstStartingStadiumLabel = new QLabel(mstPage);
        mstStartingStadiumLabel->setObjectName(QString::fromUtf8("mstStartingStadiumLabel"));
        mstStartingStadiumLabel->setGeometry(QRect(740, 60, 121, 31));
        mstTotalDistanceTraveled_2 = new QLabel(mstPage);
        mstTotalDistanceTraveled_2->setObjectName(QString::fromUtf8("mstTotalDistanceTraveled_2"));
        mstTotalDistanceTraveled_2->setGeometry(QRect(670, 650, 141, 16));
        mstResultsListWidget = new QListWidget(mstPage);
        mstResultsListWidget->setObjectName(QString::fromUtf8("mstResultsListWidget"));
        mstResultsListWidget->setGeometry(QRect(670, 230, 256, 381));
        mstPushButton = new QPushButton(mstPage);
        mstPushButton->setObjectName(QString::fromUtf8("mstPushButton"));
        mstPushButton->setGeometry(QRect(680, 160, 241, 61));
        mstStartingStadiumLineEdit = new QLineEdit(mstPage);
        mstStartingStadiumLineEdit->setObjectName(QString::fromUtf8("mstStartingStadiumLineEdit"));
        mstStartingStadiumLineEdit->setGeometry(QRect(640, 110, 321, 21));
        mstStadiumListWidget = new QListWidget(mstPage);
        mstStadiumListWidget->setObjectName(QString::fromUtf8("mstStadiumListWidget"));
        mstStadiumListWidget->setGeometry(QRect(210, 80, 291, 591));
        mstTotalDistanceTraveledLineEdit = new QLineEdit(mstPage);
        mstTotalDistanceTraveledLineEdit->setObjectName(QString::fromUtf8("mstTotalDistanceTraveledLineEdit"));
        mstTotalDistanceTraveledLineEdit->setGeometry(QRect(830, 650, 113, 20));
        takeTripStackedWidget->addWidget(mstPage);
        userStackedWidget->addWidget(takeTripPage);
        informationPage = new QWidget();
        informationPage->setObjectName(QString::fromUtf8("informationPage"));
        informationBackButton = new QPushButton(informationPage);
        informationBackButton->setObjectName(QString::fromUtf8("informationBackButton"));
        informationBackButton->setGeometry(QRect(30, 40, 121, 41));
        tabWidget = new QTabWidget(informationPage);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
        tabWidget->setGeometry(QRect(40, 100, 1141, 421));
        tabWidget->setTabPosition(QTabWidget::North);
        MajorLeagueTeam = new QWidget();
        MajorLeagueTeam->setObjectName(QString::fromUtf8("MajorLeagueTeam"));
        label_5 = new QLabel(MajorLeagueTeam);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(900, 30, 111, 16));
        label_19 = new QLabel(MajorLeagueTeam);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(930, 30, 111, 16));
        teamTableWidget_1 = new QTableWidget(MajorLeagueTeam);
        teamTableWidget_1->setObjectName(QString::fromUtf8("teamTableWidget_1"));
        teamTableWidget_1->setGeometry(QRect(10, 30, 881, 311));
        teamTableWidget_1->setMinimumSize(QSize(741, 0));
        teamTableWidget_1->setMaximumSize(QSize(16777215, 311));
        teamTableWidget_1->horizontalHeader()->setDefaultSectionSize(440);
        teamTableWidget_1->horizontalHeader()->setMinimumSectionSize(100);
        tabWidget->addTab(MajorLeagueTeam, QString());
        MajorLeagueStadium = new QWidget();
        MajorLeagueStadium->setObjectName(QString::fromUtf8("MajorLeagueStadium"));
        label_6 = new QLabel(MajorLeagueStadium);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(900, 30, 111, 16));
        label_20 = new QLabel(MajorLeagueStadium);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(930, 30, 111, 16));
        teamTableWidget_2 = new QTableWidget(MajorLeagueStadium);
        teamTableWidget_2->setObjectName(QString::fromUtf8("teamTableWidget_2"));
        teamTableWidget_2->setGeometry(QRect(10, 30, 881, 311));
        teamTableWidget_2->setMinimumSize(QSize(741, 0));
        teamTableWidget_2->setMaximumSize(QSize(16777215, 311));
        teamTableWidget_2->horizontalHeader()->setDefaultSectionSize(440);
        teamTableWidget_2->horizontalHeader()->setMinimumSectionSize(100);
        tabWidget->addTab(MajorLeagueStadium, QString());
        AmericanLeagueTeam = new QWidget();
        AmericanLeagueTeam->setObjectName(QString::fromUtf8("AmericanLeagueTeam"));
        label_7 = new QLabel(AmericanLeagueTeam);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(900, 30, 111, 16));
        label_21 = new QLabel(AmericanLeagueTeam);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(930, 30, 111, 16));
        teamTableWidget_3 = new QTableWidget(AmericanLeagueTeam);
        teamTableWidget_3->setObjectName(QString::fromUtf8("teamTableWidget_3"));
        teamTableWidget_3->setGeometry(QRect(10, 30, 881, 311));
        teamTableWidget_3->setMinimumSize(QSize(741, 0));
        teamTableWidget_3->setMaximumSize(QSize(16777215, 311));
        teamTableWidget_3->horizontalHeader()->setDefaultSectionSize(440);
        teamTableWidget_3->horizontalHeader()->setMinimumSectionSize(100);
        tabWidget->addTab(AmericanLeagueTeam, QString());
        NationalLeagueStadium = new QWidget();
        NationalLeagueStadium->setObjectName(QString::fromUtf8("NationalLeagueStadium"));
        label_4 = new QLabel(NationalLeagueStadium);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(900, 30, 111, 16));
        label_22 = new QLabel(NationalLeagueStadium);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(930, 30, 111, 16));
        teamTableWidget_4 = new QTableWidget(NationalLeagueStadium);
        teamTableWidget_4->setObjectName(QString::fromUtf8("teamTableWidget_4"));
        teamTableWidget_4->setGeometry(QRect(10, 30, 881, 311));
        teamTableWidget_4->setMinimumSize(QSize(741, 0));
        teamTableWidget_4->setMaximumSize(QSize(16777215, 311));
        teamTableWidget_4->horizontalHeader()->setDefaultSectionSize(440);
        teamTableWidget_4->horizontalHeader()->setMinimumSectionSize(100);
        tabWidget->addTab(NationalLeagueStadium, QString());
        typology = new QWidget();
        typology->setObjectName(QString::fromUtf8("typology"));
        label_8 = new QLabel(typology);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(900, 30, 111, 16));
        label_23 = new QLabel(typology);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(930, 30, 111, 16));
        teamTableWidget_5 = new QTableWidget(typology);
        teamTableWidget_5->setObjectName(QString::fromUtf8("teamTableWidget_5"));
        teamTableWidget_5->setGeometry(QRect(10, 30, 881, 311));
        teamTableWidget_5->setMinimumSize(QSize(741, 0));
        teamTableWidget_5->setMaximumSize(QSize(16777215, 311));
        teamTableWidget_5->horizontalHeader()->setDefaultSectionSize(293);
        teamTableWidget_5->horizontalHeader()->setMinimumSectionSize(100);
        tabWidget->addTab(typology, QString());
        openRoofType = new QWidget();
        openRoofType->setObjectName(QString::fromUtf8("openRoofType"));
        label_9 = new QLabel(openRoofType);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(900, 30, 111, 16));
        label_24 = new QLabel(openRoofType);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(930, 30, 111, 16));
        teamTableWidget_6 = new QTableWidget(openRoofType);
        teamTableWidget_6->setObjectName(QString::fromUtf8("teamTableWidget_6"));
        teamTableWidget_6->setGeometry(QRect(10, 30, 881, 311));
        teamTableWidget_6->setMinimumSize(QSize(741, 0));
        teamTableWidget_6->setMaximumSize(QSize(16777215, 311));
        teamTableWidget_6->horizontalHeader()->setDefaultSectionSize(293);
        teamTableWidget_6->horizontalHeader()->setMinimumSectionSize(100);
        tabWidget->addTab(openRoofType, QString());
        dateOpened = new QWidget();
        dateOpened->setObjectName(QString::fromUtf8("dateOpened"));
        label_15 = new QLabel(dateOpened);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(900, 30, 111, 16));
        label_25 = new QLabel(dateOpened);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(930, 30, 111, 16));
        teamTableWidget_7 = new QTableWidget(dateOpened);
        teamTableWidget_7->setObjectName(QString::fromUtf8("teamTableWidget_7"));
        teamTableWidget_7->setGeometry(QRect(10, 30, 881, 311));
        teamTableWidget_7->setMinimumSize(QSize(741, 0));
        teamTableWidget_7->setMaximumSize(QSize(16777215, 311));
        teamTableWidget_7->horizontalHeader()->setDefaultSectionSize(293);
        teamTableWidget_7->horizontalHeader()->setMinimumSectionSize(100);
        tabWidget->addTab(dateOpened, QString());
        seatingCapacity = new QWidget();
        seatingCapacity->setObjectName(QString::fromUtf8("seatingCapacity"));
        label_16 = new QLabel(seatingCapacity);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(900, 30, 111, 16));
        label_26 = new QLabel(seatingCapacity);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(930, 30, 111, 16));
        teamTableWidget_8 = new QTableWidget(seatingCapacity);
        teamTableWidget_8->setObjectName(QString::fromUtf8("teamTableWidget_8"));
        teamTableWidget_8->setGeometry(QRect(10, 30, 881, 311));
        teamTableWidget_8->setMinimumSize(QSize(741, 0));
        teamTableWidget_8->setMaximumSize(QSize(16777215, 311));
        teamTableWidget_8->horizontalHeader()->setDefaultSectionSize(293);
        teamTableWidget_8->horizontalHeader()->setMinimumSectionSize(100);
        label_31 = new QLabel(seatingCapacity);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(900, 50, 141, 16));
        label_32 = new QLabel(seatingCapacity);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(1040, 50, 141, 16));
        tabWidget->addTab(seatingCapacity, QString());
        greatestDistanceCenter = new QWidget();
        greatestDistanceCenter->setObjectName(QString::fromUtf8("greatestDistanceCenter"));
        teamTableWidget_9 = new QTableWidget(greatestDistanceCenter);
        teamTableWidget_9->setObjectName(QString::fromUtf8("teamTableWidget_9"));
        teamTableWidget_9->setGeometry(QRect(10, 30, 881, 311));
        teamTableWidget_9->setMinimumSize(QSize(741, 0));
        teamTableWidget_9->setMaximumSize(QSize(16777215, 311));
        teamTableWidget_9->horizontalHeader()->setDefaultSectionSize(293);
        teamTableWidget_9->horizontalHeader()->setMinimumSectionSize(100);
        label_17 = new QLabel(greatestDistanceCenter);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(900, 30, 111, 16));
        label_27 = new QLabel(greatestDistanceCenter);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(930, 30, 111, 16));
        tabWidget->addTab(greatestDistanceCenter, QString());
        smallestDistanceCenter = new QWidget();
        smallestDistanceCenter->setObjectName(QString::fromUtf8("smallestDistanceCenter"));
        label_18 = new QLabel(smallestDistanceCenter);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(900, 30, 111, 16));
        label_28 = new QLabel(smallestDistanceCenter);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(930, 30, 111, 16));
        teamTableWidget_10 = new QTableWidget(smallestDistanceCenter);
        teamTableWidget_10->setObjectName(QString::fromUtf8("teamTableWidget_10"));
        teamTableWidget_10->setGeometry(QRect(10, 30, 881, 311));
        teamTableWidget_10->setMinimumSize(QSize(741, 0));
        teamTableWidget_10->setMaximumSize(QSize(16777215, 311));
        teamTableWidget_10->horizontalHeader()->setDefaultSectionSize(293);
        teamTableWidget_10->horizontalHeader()->setMinimumSectionSize(100);
        tabWidget->addTab(smallestDistanceCenter, QString());
        label_12 = new QLabel(informationPage);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(490, 80, 181, 16));
        userStackedWidget->addWidget(informationPage);
        viewStadiumsPage = new QWidget();
        viewStadiumsPage->setObjectName(QString::fromUtf8("viewStadiumsPage"));
        souvenirListWidget_2 = new QListWidget(viewStadiumsPage);
        souvenirListWidget_2->setObjectName(QString::fromUtf8("souvenirListWidget_2"));
        souvenirListWidget_2->setGeometry(QRect(900, 120, 191, 271));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        QBrush brush10(QColor(0, 170, 255, 255));
        brush10.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush10);
        souvenirListWidget_2->setPalette(palette3);
        stadiumListWidget_2 = new QListWidget(viewStadiumsPage);
        stadiumListWidget_2->setObjectName(QString::fromUtf8("stadiumListWidget_2"));
        stadiumListWidget_2->setGeometry(QRect(20, 120, 451, 591));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Active, QPalette::Button, brush6);
        palette4.setBrush(QPalette::Active, QPalette::Light, brush6);
        palette4.setBrush(QPalette::Active, QPalette::Midlight, brush6);
        QBrush brush11(QColor(127, 127, 127, 255));
        brush11.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::Dark, brush11);
        QBrush brush12(QColor(170, 170, 170, 255));
        brush12.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::Mid, brush12);
        palette4.setBrush(QPalette::Active, QPalette::Text, brush);
        palette4.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette4.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette4.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette4.setBrush(QPalette::Active, QPalette::Window, brush6);
        palette4.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette4.setBrush(QPalette::Active, QPalette::AlternateBase, brush6);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette4.setBrush(QPalette::Active, QPalette::PlaceholderText, brush9);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Button, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::Light, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::Midlight, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::Dark, brush11);
        palette4.setBrush(QPalette::Inactive, QPalette::Mid, brush12);
        palette4.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::Window, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush9);
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush11);
        palette4.setBrush(QPalette::Disabled, QPalette::Button, brush6);
        palette4.setBrush(QPalette::Disabled, QPalette::Light, brush6);
        palette4.setBrush(QPalette::Disabled, QPalette::Midlight, brush6);
        palette4.setBrush(QPalette::Disabled, QPalette::Dark, brush11);
        palette4.setBrush(QPalette::Disabled, QPalette::Mid, brush12);
        palette4.setBrush(QPalette::Disabled, QPalette::Text, brush11);
        palette4.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette4.setBrush(QPalette::Disabled, QPalette::ButtonText, brush11);
        palette4.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette4.setBrush(QPalette::Disabled, QPalette::Window, brush6);
        palette4.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush6);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush9);
        stadiumListWidget_2->setPalette(palette4);
        groupBox_2 = new QGroupBox(viewStadiumsPage);
        groupBox_2->setObjectName(QString::fromUtf8("groupBox_2"));
        groupBox_2->setGeometry(QRect(580, 410, 521, 281));
        capacityLabel_2 = new QLabel(groupBox_2);
        capacityLabel_2->setObjectName(QString::fromUtf8("capacityLabel_2"));
        capacityLabel_2->setGeometry(QRect(50, 40, 51, 16));
        typologyLabel_2 = new QLabel(groupBox_2);
        typologyLabel_2->setObjectName(QString::fromUtf8("typologyLabel_2"));
        typologyLabel_2->setGeometry(QRect(50, 130, 61, 16));
        distToCenterLineEdit_2 = new QLineEdit(groupBox_2);
        distToCenterLineEdit_2->setObjectName(QString::fromUtf8("distToCenterLineEdit_2"));
        distToCenterLineEdit_2->setGeometry(QRect(360, 160, 113, 20));
        roofTypeLabel_2 = new QLabel(groupBox_2);
        roofTypeLabel_2->setObjectName(QString::fromUtf8("roofTypeLabel_2"));
        roofTypeLabel_2->setGeometry(QRect(390, 40, 61, 16));
        surfaceLabel_2 = new QLabel(groupBox_2);
        surfaceLabel_2->setObjectName(QString::fromUtf8("surfaceLabel_2"));
        surfaceLabel_2->setGeometry(QRect(220, 40, 47, 13));
        capacityLineEdit_2 = new QLineEdit(groupBox_2);
        capacityLineEdit_2->setObjectName(QString::fromUtf8("capacityLineEdit_2"));
        capacityLineEdit_2->setGeometry(QRect(20, 80, 113, 20));
        roofTypeLineEdit_2 = new QLineEdit(groupBox_2);
        roofTypeLineEdit_2->setObjectName(QString::fromUtf8("roofTypeLineEdit_2"));
        roofTypeLineEdit_2->setGeometry(QRect(360, 80, 113, 20));
        surfaceLineEdit_2 = new QLineEdit(groupBox_2);
        surfaceLineEdit_2->setObjectName(QString::fromUtf8("surfaceLineEdit_2"));
        surfaceLineEdit_2->setGeometry(QRect(190, 80, 113, 20));
        dateOpenedLineEdit_2 = new QLineEdit(groupBox_2);
        dateOpenedLineEdit_2->setObjectName(QString::fromUtf8("dateOpenedLineEdit_2"));
        dateOpenedLineEdit_2->setGeometry(QRect(100, 230, 113, 20));
        dateLabel_2 = new QLabel(groupBox_2);
        dateLabel_2->setObjectName(QString::fromUtf8("dateLabel_2"));
        dateLabel_2->setGeometry(QRect(120, 200, 81, 16));
        typologyLineEdit_2 = new QLineEdit(groupBox_2);
        typologyLineEdit_2->setObjectName(QString::fromUtf8("typologyLineEdit_2"));
        typologyLineEdit_2->setGeometry(QRect(20, 160, 113, 20));
        distToCenterLabel_2 = new QLabel(groupBox_2);
        distToCenterLabel_2->setObjectName(QString::fromUtf8("distToCenterLabel_2"));
        distToCenterLabel_2->setGeometry(QRect(360, 130, 131, 16));
        locationLineEdit_2 = new QLineEdit(groupBox_2);
        locationLineEdit_2->setObjectName(QString::fromUtf8("locationLineEdit_2"));
        locationLineEdit_2->setGeometry(QRect(162, 160, 171, 20));
        locationLabel_2 = new QLabel(groupBox_2);
        locationLabel_2->setObjectName(QString::fromUtf8("locationLabel_2"));
        locationLabel_2->setGeometry(QRect(230, 130, 81, 16));
        leagueLineEdit_2 = new QLineEdit(groupBox_2);
        leagueLineEdit_2->setObjectName(QString::fromUtf8("leagueLineEdit_2"));
        leagueLineEdit_2->setGeometry(QRect(290, 230, 113, 20));
        leagueLabel_2 = new QLabel(groupBox_2);
        leagueLabel_2->setObjectName(QString::fromUtf8("leagueLabel_2"));
        leagueLabel_2->setGeometry(QRect(320, 200, 81, 16));
        label_13 = new QLabel(viewStadiumsPage);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(980, 90, 61, 16));
        viewStadiumsBackButton = new QPushButton(viewStadiumsPage);
        viewStadiumsBackButton->setObjectName(QString::fromUtf8("viewStadiumsBackButton"));
        viewStadiumsBackButton->setGeometry(QRect(20, 20, 121, 41));
        souvenirPriceListWidget_2 = new QListWidget(viewStadiumsPage);
        souvenirPriceListWidget_2->setObjectName(QString::fromUtf8("souvenirPriceListWidget_2"));
        souvenirPriceListWidget_2->setGeometry(QRect(1090, 120, 51, 271));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette5.setBrush(QPalette::Disabled, QPalette::Base, brush10);
        souvenirPriceListWidget_2->setPalette(palette5);
        label_14 = new QLabel(viewStadiumsPage);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(210, 90, 91, 21));
        label_14->setFont(font3);
        userStackedWidget->addWidget(viewStadiumsPage);
        primaryPageStackedWidget->addWidget(userPage);
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QString::fromUtf8("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1200, 21));
        menuFile = new QMenu(menuBar);
        menuFile->setObjectName(QString::fromUtf8("menuFile"));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QString::fromUtf8("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QString::fromUtf8("statusBar"));
        MainWindow->setStatusBar(statusBar);

        menuBar->addAction(menuFile->menuAction());
        menuFile->addAction(actionLogout);

        retranslateUi(MainWindow);

        primaryPageStackedWidget->setCurrentIndex(1);
        adminStackedWidget->setCurrentIndex(1);
        userStackedWidget->setCurrentIndex(3);
        takeTripStackedWidget->setCurrentIndex(0);
        tabWidget->setCurrentIndex(2);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", nullptr));
        actionLogout->setText(QApplication::translate("MainWindow", "Logout", nullptr));
        label->setText(QApplication::translate("MainWindow", "Ballgame Boogaloo", nullptr));
        label_2->setText(QApplication::translate("MainWindow", "Please Login", nullptr));
        usernameLabel->setText(QApplication::translate("MainWindow", "Username", nullptr));
        passwordLabel->setText(QApplication::translate("MainWindow", "Password ", nullptr));
        checkBox_showPW->setText(QApplication::translate("MainWindow", "Show", nullptr));
        loginPushButton->setText(QApplication::translate("MainWindow", "Login", nullptr));
        label_29->setText(QApplication::translate("MainWindow", "ALAYO", nullptr));
        welcomeLabel_admin->setText(QApplication::translate("MainWindow", "Welcome, Admin!", nullptr));
        informationButton_admin->setText(QApplication::translate("MainWindow", "View Stadiums", nullptr));
        takeTripButton_admin->setText(QApplication::translate("MainWindow", "Take a Trip", nullptr));
        manageStadiumsButton->setText(QApplication::translate("MainWindow", "Manage Stadiums", nullptr));
        AlayoLogoLabel->setText(QString());
        label_3->setText(QApplication::translate("MainWindow", "Teams", nullptr));
        label_10->setText(QApplication::translate("MainWindow", "Souvenirs", nullptr));
        manageStadiumsBackButton->setText(QApplication::translate("MainWindow", "Back", nullptr));
        groupBox->setTitle(QApplication::translate("MainWindow", "Stadium Attributes", nullptr));
        capacityLabel->setText(QApplication::translate("MainWindow", "Capacity", nullptr));
        typologyLabel->setText(QApplication::translate("MainWindow", "Typology", nullptr));
        roofTypeLabel->setText(QApplication::translate("MainWindow", "Roof Type", nullptr));
        surfaceLabel->setText(QApplication::translate("MainWindow", "Surface", nullptr));
        dateLabel->setText(QApplication::translate("MainWindow", "Date Opened", nullptr));
        distToCenterLabel->setText(QApplication::translate("MainWindow", "Dist. to Center Field", nullptr));
        newStadiumLabel->setText(QApplication::translate("MainWindow", "Stadium", nullptr));
        locationLabel->setText(QApplication::translate("MainWindow", "Location", nullptr));
        leagueLabel->setText(QApplication::translate("MainWindow", "League", nullptr));
        changeSouvenirLabel->setText(QApplication::translate("MainWindow", "Changing Souvenir:", nullptr));
        changeSouvenirLabel_2->setText(QApplication::translate("MainWindow", "Add Souvenir", nullptr));
        souvenirAddAllTeamsCheckbox->setText(QApplication::translate("MainWindow", "All Teams", nullptr));
        addSouvenirPushButton->setText(QApplication::translate("MainWindow", "Add", nullptr));
        souvenirAddItemNameLabel->setText(QApplication::translate("MainWindow", "Item Name", nullptr));
        souvenirAddItemPriceLabel->setText(QApplication::translate("MainWindow", "Item Price", nullptr));
        deleteSouvenirPushButton->setText(QApplication::translate("MainWindow", "Delete", nullptr));
        souvenirChangingName->setText(QString());
        changeSouvenirPushButton->setText(QApplication::translate("MainWindow", "Change Souvenir", nullptr));
        changeSouvenirLabel_3->setText(QApplication::translate("MainWindow", "Name:", nullptr));
        changeSouvenirLabel_4->setText(QApplication::translate("MainWindow", " Price:", nullptr));
        souvenirChangeAllTeamsCheckbox->setText(QApplication::translate("MainWindow", "All Teams", nullptr));
        souvenirDeleteAllTeamsCheckbox->setText(QApplication::translate("MainWindow", "All Teams", nullptr));
        AddTeamButton->setText(QApplication::translate("MainWindow", "Add Team", nullptr));
        ReinitializeButton->setText(QApplication::translate("MainWindow", "Reinitialize", nullptr));
        takeTripButton_user->setText(QApplication::translate("MainWindow", "Take a Trip", nullptr));
        informationButton_user->setText(QApplication::translate("MainWindow", "Information", nullptr));
        viewStadiumsButton->setText(QApplication::translate("MainWindow", "View Stadiums", nullptr));
        welcomeLabel_admin_2->setText(QApplication::translate("MainWindow", "Welcome, User!", nullptr));
        AlayoLogoLabel_2->setText(QString());
        visitSingleButton->setText(QApplication::translate("MainWindow", "Visit One Stadium", nullptr));
        visitMultipleButton->setText(QApplication::translate("MainWindow", "Visit Custom Stadiums", nullptr));
        TakeATripLabel->setText(QApplication::translate("MainWindow", "Take a Trip!", nullptr));
        takeTripPageBackButton->setText(QApplication::translate("MainWindow", "Back", nullptr));
        performdfsButton->setText(QApplication::translate("MainWindow", "Perform DFS", nullptr));
        performbfsButton->setText(QApplication::translate("MainWindow", "Perform BFS", nullptr));
        performmstButton->setText(QApplication::translate("MainWindow", "Perform MST", nullptr));
        MLBImageLabel->setText(QString());
        label_30->setText(QApplication::translate("MainWindow", "Stadiums", nullptr));
        optimizeButton->setText(QApplication::translate("MainWindow", "Optimize", nullptr));
        goButton->setText(QApplication::translate("MainWindow", "Go", nullptr));
        multipleSelectionPageBackButton->setText(QApplication::translate("MainWindow", "Back", nullptr));
        selectAllTeamsCheckBox->setText(QApplication::translate("MainWindow", "Select All Teams", nullptr));
        singleSelectionPageBackButton->setText(QApplication::translate("MainWindow", "Back", nullptr));
        label_11->setText(QApplication::translate("MainWindow", "The total distance you have traveled: ", nullptr));
        dfsPageBackButton->setText(QApplication::translate("MainWindow", "Back", nullptr));
        dfsChooseStartingStadiumLabel->setText(QApplication::translate("MainWindow", "Choose a starting stadium:", nullptr));
        dfsStartingStadiumLabel->setText(QApplication::translate("MainWindow", "Starting Stadium", nullptr));
        dfsPushButton->setText(QApplication::translate("MainWindow", "Perform DFS", nullptr));
        dfsTotalDistanceTraveledLabel->setText(QApplication::translate("MainWindow", "Total Distance Traveled", nullptr));
        bfsTotalDistanceTraveled->setText(QApplication::translate("MainWindow", "Total Distance Traveled", nullptr));
        bfsPushButton->setText(QApplication::translate("MainWindow", "Perform BFS", nullptr));
        bfsPageBackButton->setText(QApplication::translate("MainWindow", "Back", nullptr));
        bfsStartingStadiumLabel->setText(QApplication::translate("MainWindow", "Starting Stadium", nullptr));
        bfsChooseStartingStadiumLabel->setText(QApplication::translate("MainWindow", "Choose a starting stadium:", nullptr));
        mstBackButton->setText(QApplication::translate("MainWindow", "Back", nullptr));
        mstChooseStartingStadiumLabel->setText(QApplication::translate("MainWindow", "Choose a starting stadium:", nullptr));
        mstStartingStadiumLabel->setText(QApplication::translate("MainWindow", "Starting Stadium", nullptr));
        mstTotalDistanceTraveled_2->setText(QApplication::translate("MainWindow", "Total Distance Traveled", nullptr));
        mstPushButton->setText(QApplication::translate("MainWindow", "Perform MST", nullptr));
        informationBackButton->setText(QApplication::translate("MainWindow", "Back", nullptr));
        label_5->setText(QApplication::translate("MainWindow", "Size:", nullptr));
        label_19->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(MajorLeagueTeam), QApplication::translate("MainWindow", "Major-Name", nullptr));
        label_6->setText(QApplication::translate("MainWindow", "Size:", nullptr));
        label_20->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(MajorLeagueStadium), QApplication::translate("MainWindow", "Major-Stadium", nullptr));
        label_7->setText(QApplication::translate("MainWindow", "Size:", nullptr));
        label_21->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(AmericanLeagueTeam), QApplication::translate("MainWindow", "American-Name", nullptr));
        label_4->setText(QApplication::translate("MainWindow", "Size:", nullptr));
        label_22->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(NationalLeagueStadium), QApplication::translate("MainWindow", "National-Stadium", nullptr));
        label_8->setText(QApplication::translate("MainWindow", "Size:", nullptr));
        label_23->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(typology), QApplication::translate("MainWindow", "Park Typology", nullptr));
        label_9->setText(QApplication::translate("MainWindow", "Size:", nullptr));
        label_24->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(openRoofType), QApplication::translate("MainWindow", "Roof Type", nullptr));
        label_15->setText(QApplication::translate("MainWindow", "Size:", nullptr));
        label_25->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(dateOpened), QApplication::translate("MainWindow", "Date", nullptr));
        label_16->setText(QApplication::translate("MainWindow", "Size:", nullptr));
        label_26->setText(QString());
        label_31->setText(QApplication::translate("MainWindow", "Total Seating Capacity: ", nullptr));
        label_32->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(seatingCapacity), QApplication::translate("MainWindow", "Seating Capacity", nullptr));
        label_17->setText(QApplication::translate("MainWindow", "Size:", nullptr));
        label_27->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(greatestDistanceCenter), QApplication::translate("MainWindow", "Greatest Center Field", nullptr));
        label_18->setText(QApplication::translate("MainWindow", "Size:", nullptr));
        label_28->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(smallestDistanceCenter), QApplication::translate("MainWindow", "Smallest Center Field", nullptr));
        label_12->setText(QApplication::translate("MainWindow", "View Information by Category", nullptr));
        groupBox_2->setTitle(QApplication::translate("MainWindow", "Stadium Attributes", nullptr));
        capacityLabel_2->setText(QApplication::translate("MainWindow", "Capacity", nullptr));
        typologyLabel_2->setText(QApplication::translate("MainWindow", "Typology", nullptr));
        roofTypeLabel_2->setText(QApplication::translate("MainWindow", "Roof Type", nullptr));
        surfaceLabel_2->setText(QApplication::translate("MainWindow", "Surface", nullptr));
        dateLabel_2->setText(QApplication::translate("MainWindow", "Date Opened", nullptr));
        distToCenterLabel_2->setText(QApplication::translate("MainWindow", "Dist. to Center Field", nullptr));
        locationLabel_2->setText(QApplication::translate("MainWindow", "Location", nullptr));
        leagueLabel_2->setText(QApplication::translate("MainWindow", "League", nullptr));
        label_13->setText(QApplication::translate("MainWindow", "Souvenirs", nullptr));
        viewStadiumsBackButton->setText(QApplication::translate("MainWindow", "Back", nullptr));
        label_14->setText(QApplication::translate("MainWindow", "Teams", nullptr));
        menuFile->setTitle(QApplication::translate("MainWindow", "Logout", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
